// Generated by delombok at Wed Apr 13 12:12:31 CST 2022
package com.puboot.module.admin.model;

import com.baomidou.mybatisplus.annotation.TableField;
import com.puboot.module.admin.vo.base.BaseVo;
import java.util.List;

/**
 * @author Linzhaoguan
 * @version V1.0
 * @date 2019年9月11日
 */
public class BizArticle extends BaseVo {
    private static final long serialVersionUID = 7238198006412851176L;
    private String title;
    private String userId;
    private String author;
    private String coverImage;
    private String qrcodePath;
    private Boolean isMarkdown;
    private String content;
    private String contentMd;
    private Integer top;
    private Integer categoryId;
    private Integer status;
    private Integer recommended;
    private Integer slider;
    private String sliderImg;
    private Integer original;
    private String description;
    private String keywords;
    private Integer comment;
    @TableField(exist = false)
    private Integer lookCount = 0;
    @TableField(exist = false)
    private Integer commentCount = 0;
    @TableField(exist = false)
    private Integer loveCount = 0;
    @TableField(exist = false)
    private Integer newFlag = 0;
    @TableField(exist = false)
    List<BizTags> tags;
    @TableField(exist = false)
    BizCategory bizCategory;

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof BizArticle)) return false;
        final BizArticle other = (BizArticle) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (!super.equals(o)) return false;
        final java.lang.Object this$title = this.getTitle();
        final java.lang.Object other$title = other.getTitle();
        if (this$title == null ? other$title != null : !this$title.equals(other$title)) return false;
        final java.lang.Object this$userId = this.getUserId();
        final java.lang.Object other$userId = other.getUserId();
        if (this$userId == null ? other$userId != null : !this$userId.equals(other$userId)) return false;
        final java.lang.Object this$author = this.getAuthor();
        final java.lang.Object other$author = other.getAuthor();
        if (this$author == null ? other$author != null : !this$author.equals(other$author)) return false;
        final java.lang.Object this$coverImage = this.getCoverImage();
        final java.lang.Object other$coverImage = other.getCoverImage();
        if (this$coverImage == null ? other$coverImage != null : !this$coverImage.equals(other$coverImage)) return false;
        final java.lang.Object this$qrcodePath = this.getQrcodePath();
        final java.lang.Object other$qrcodePath = other.getQrcodePath();
        if (this$qrcodePath == null ? other$qrcodePath != null : !this$qrcodePath.equals(other$qrcodePath)) return false;
        final java.lang.Object this$isMarkdown = this.getIsMarkdown();
        final java.lang.Object other$isMarkdown = other.getIsMarkdown();
        if (this$isMarkdown == null ? other$isMarkdown != null : !this$isMarkdown.equals(other$isMarkdown)) return false;
        final java.lang.Object this$content = this.getContent();
        final java.lang.Object other$content = other.getContent();
        if (this$content == null ? other$content != null : !this$content.equals(other$content)) return false;
        final java.lang.Object this$contentMd = this.getContentMd();
        final java.lang.Object other$contentMd = other.getContentMd();
        if (this$contentMd == null ? other$contentMd != null : !this$contentMd.equals(other$contentMd)) return false;
        final java.lang.Object this$top = this.getTop();
        final java.lang.Object other$top = other.getTop();
        if (this$top == null ? other$top != null : !this$top.equals(other$top)) return false;
        final java.lang.Object this$categoryId = this.getCategoryId();
        final java.lang.Object other$categoryId = other.getCategoryId();
        if (this$categoryId == null ? other$categoryId != null : !this$categoryId.equals(other$categoryId)) return false;
        final java.lang.Object this$status = this.getStatus();
        final java.lang.Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
        final java.lang.Object this$recommended = this.getRecommended();
        final java.lang.Object other$recommended = other.getRecommended();
        if (this$recommended == null ? other$recommended != null : !this$recommended.equals(other$recommended)) return false;
        final java.lang.Object this$slider = this.getSlider();
        final java.lang.Object other$slider = other.getSlider();
        if (this$slider == null ? other$slider != null : !this$slider.equals(other$slider)) return false;
        final java.lang.Object this$sliderImg = this.getSliderImg();
        final java.lang.Object other$sliderImg = other.getSliderImg();
        if (this$sliderImg == null ? other$sliderImg != null : !this$sliderImg.equals(other$sliderImg)) return false;
        final java.lang.Object this$original = this.getOriginal();
        final java.lang.Object other$original = other.getOriginal();
        if (this$original == null ? other$original != null : !this$original.equals(other$original)) return false;
        final java.lang.Object this$description = this.getDescription();
        final java.lang.Object other$description = other.getDescription();
        if (this$description == null ? other$description != null : !this$description.equals(other$description)) return false;
        final java.lang.Object this$keywords = this.getKeywords();
        final java.lang.Object other$keywords = other.getKeywords();
        if (this$keywords == null ? other$keywords != null : !this$keywords.equals(other$keywords)) return false;
        final java.lang.Object this$comment = this.getComment();
        final java.lang.Object other$comment = other.getComment();
        if (this$comment == null ? other$comment != null : !this$comment.equals(other$comment)) return false;
        final java.lang.Object this$lookCount = this.getLookCount();
        final java.lang.Object other$lookCount = other.getLookCount();
        if (this$lookCount == null ? other$lookCount != null : !this$lookCount.equals(other$lookCount)) return false;
        final java.lang.Object this$commentCount = this.getCommentCount();
        final java.lang.Object other$commentCount = other.getCommentCount();
        if (this$commentCount == null ? other$commentCount != null : !this$commentCount.equals(other$commentCount)) return false;
        final java.lang.Object this$loveCount = this.getLoveCount();
        final java.lang.Object other$loveCount = other.getLoveCount();
        if (this$loveCount == null ? other$loveCount != null : !this$loveCount.equals(other$loveCount)) return false;
        final java.lang.Object this$newFlag = this.getNewFlag();
        final java.lang.Object other$newFlag = other.getNewFlag();
        if (this$newFlag == null ? other$newFlag != null : !this$newFlag.equals(other$newFlag)) return false;
        final java.lang.Object this$tags = this.getTags();
        final java.lang.Object other$tags = other.getTags();
        if (this$tags == null ? other$tags != null : !this$tags.equals(other$tags)) return false;
        final java.lang.Object this$bizCategory = this.getBizCategory();
        final java.lang.Object other$bizCategory = other.getBizCategory();
        if (this$bizCategory == null ? other$bizCategory != null : !this$bizCategory.equals(other$bizCategory)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof BizArticle;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = super.hashCode();
        final java.lang.Object $title = this.getTitle();
        result = result * PRIME + ($title == null ? 43 : $title.hashCode());
        final java.lang.Object $userId = this.getUserId();
        result = result * PRIME + ($userId == null ? 43 : $userId.hashCode());
        final java.lang.Object $author = this.getAuthor();
        result = result * PRIME + ($author == null ? 43 : $author.hashCode());
        final java.lang.Object $coverImage = this.getCoverImage();
        result = result * PRIME + ($coverImage == null ? 43 : $coverImage.hashCode());
        final java.lang.Object $qrcodePath = this.getQrcodePath();
        result = result * PRIME + ($qrcodePath == null ? 43 : $qrcodePath.hashCode());
        final java.lang.Object $isMarkdown = this.getIsMarkdown();
        result = result * PRIME + ($isMarkdown == null ? 43 : $isMarkdown.hashCode());
        final java.lang.Object $content = this.getContent();
        result = result * PRIME + ($content == null ? 43 : $content.hashCode());
        final java.lang.Object $contentMd = this.getContentMd();
        result = result * PRIME + ($contentMd == null ? 43 : $contentMd.hashCode());
        final java.lang.Object $top = this.getTop();
        result = result * PRIME + ($top == null ? 43 : $top.hashCode());
        final java.lang.Object $categoryId = this.getCategoryId();
        result = result * PRIME + ($categoryId == null ? 43 : $categoryId.hashCode());
        final java.lang.Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        final java.lang.Object $recommended = this.getRecommended();
        result = result * PRIME + ($recommended == null ? 43 : $recommended.hashCode());
        final java.lang.Object $slider = this.getSlider();
        result = result * PRIME + ($slider == null ? 43 : $slider.hashCode());
        final java.lang.Object $sliderImg = this.getSliderImg();
        result = result * PRIME + ($sliderImg == null ? 43 : $sliderImg.hashCode());
        final java.lang.Object $original = this.getOriginal();
        result = result * PRIME + ($original == null ? 43 : $original.hashCode());
        final java.lang.Object $description = this.getDescription();
        result = result * PRIME + ($description == null ? 43 : $description.hashCode());
        final java.lang.Object $keywords = this.getKeywords();
        result = result * PRIME + ($keywords == null ? 43 : $keywords.hashCode());
        final java.lang.Object $comment = this.getComment();
        result = result * PRIME + ($comment == null ? 43 : $comment.hashCode());
        final java.lang.Object $lookCount = this.getLookCount();
        result = result * PRIME + ($lookCount == null ? 43 : $lookCount.hashCode());
        final java.lang.Object $commentCount = this.getCommentCount();
        result = result * PRIME + ($commentCount == null ? 43 : $commentCount.hashCode());
        final java.lang.Object $loveCount = this.getLoveCount();
        result = result * PRIME + ($loveCount == null ? 43 : $loveCount.hashCode());
        final java.lang.Object $newFlag = this.getNewFlag();
        result = result * PRIME + ($newFlag == null ? 43 : $newFlag.hashCode());
        final java.lang.Object $tags = this.getTags();
        result = result * PRIME + ($tags == null ? 43 : $tags.hashCode());
        final java.lang.Object $bizCategory = this.getBizCategory();
        result = result * PRIME + ($bizCategory == null ? 43 : $bizCategory.hashCode());
        return result;
    }

    @java.lang.SuppressWarnings("all")
    public BizArticle() {
    }

    @java.lang.SuppressWarnings("all")
    public String getTitle() {
        return this.title;
    }

    @java.lang.SuppressWarnings("all")
    public String getUserId() {
        return this.userId;
    }

    @java.lang.SuppressWarnings("all")
    public String getAuthor() {
        return this.author;
    }

    @java.lang.SuppressWarnings("all")
    public String getCoverImage() {
        return this.coverImage;
    }

    @java.lang.SuppressWarnings("all")
    public String getQrcodePath() {
        return this.qrcodePath;
    }

    @java.lang.SuppressWarnings("all")
    public Boolean getIsMarkdown() {
        return this.isMarkdown;
    }

    @java.lang.SuppressWarnings("all")
    public String getContent() {
        return this.content;
    }

    @java.lang.SuppressWarnings("all")
    public String getContentMd() {
        return this.contentMd;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getTop() {
        return this.top;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getCategoryId() {
        return this.categoryId;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getRecommended() {
        return this.recommended;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getSlider() {
        return this.slider;
    }

    @java.lang.SuppressWarnings("all")
    public String getSliderImg() {
        return this.sliderImg;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getOriginal() {
        return this.original;
    }

    @java.lang.SuppressWarnings("all")
    public String getDescription() {
        return this.description;
    }

    @java.lang.SuppressWarnings("all")
    public String getKeywords() {
        return this.keywords;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getComment() {
        return this.comment;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getLookCount() {
        return this.lookCount;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getCommentCount() {
        return this.commentCount;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getLoveCount() {
        return this.loveCount;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getNewFlag() {
        return this.newFlag;
    }

    @java.lang.SuppressWarnings("all")
    public List<BizTags> getTags() {
        return this.tags;
    }

    @java.lang.SuppressWarnings("all")
    public BizCategory getBizCategory() {
        return this.bizCategory;
    }

    @java.lang.SuppressWarnings("all")
    public BizArticle setTitle(final String title) {
        this.title = title;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public BizArticle setUserId(final String userId) {
        this.userId = userId;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public BizArticle setAuthor(final String author) {
        this.author = author;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public BizArticle setCoverImage(final String coverImage) {
        this.coverImage = coverImage;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public BizArticle setQrcodePath(final String qrcodePath) {
        this.qrcodePath = qrcodePath;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public BizArticle setIsMarkdown(final Boolean isMarkdown) {
        this.isMarkdown = isMarkdown;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public BizArticle setContent(final String content) {
        this.content = content;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public BizArticle setContentMd(final String contentMd) {
        this.contentMd = contentMd;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public BizArticle setTop(final Integer top) {
        this.top = top;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public BizArticle setCategoryId(final Integer categoryId) {
        this.categoryId = categoryId;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public BizArticle setStatus(final Integer status) {
        this.status = status;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public BizArticle setRecommended(final Integer recommended) {
        this.recommended = recommended;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public BizArticle setSlider(final Integer slider) {
        this.slider = slider;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public BizArticle setSliderImg(final String sliderImg) {
        this.sliderImg = sliderImg;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public BizArticle setOriginal(final Integer original) {
        this.original = original;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public BizArticle setDescription(final String description) {
        this.description = description;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public BizArticle setKeywords(final String keywords) {
        this.keywords = keywords;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public BizArticle setComment(final Integer comment) {
        this.comment = comment;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public BizArticle setLookCount(final Integer lookCount) {
        this.lookCount = lookCount;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public BizArticle setCommentCount(final Integer commentCount) {
        this.commentCount = commentCount;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public BizArticle setLoveCount(final Integer loveCount) {
        this.loveCount = loveCount;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public BizArticle setNewFlag(final Integer newFlag) {
        this.newFlag = newFlag;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public BizArticle setTags(final List<BizTags> tags) {
        this.tags = tags;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public BizArticle setBizCategory(final BizCategory bizCategory) {
        this.bizCategory = bizCategory;
        return this;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "BizArticle(title=" + this.getTitle() + ", userId=" + this.getUserId() + ", author=" + this.getAuthor() + ", coverImage=" + this.getCoverImage() + ", qrcodePath=" + this.getQrcodePath() + ", isMarkdown=" + this.getIsMarkdown() + ", content=" + this.getContent() + ", contentMd=" + this.getContentMd() + ", top=" + this.getTop() + ", categoryId=" + this.getCategoryId() + ", status=" + this.getStatus() + ", recommended=" + this.getRecommended() + ", slider=" + this.getSlider() + ", sliderImg=" + this.getSliderImg() + ", original=" + this.getOriginal() + ", description=" + this.getDescription() + ", keywords=" + this.getKeywords() + ", comment=" + this.getComment() + ", lookCount=" + this.getLookCount() + ", commentCount=" + this.getCommentCount() + ", loveCount=" + this.getLoveCount() + ", newFlag=" + this.getNewFlag() + ", tags=" + this.getTags() + ", bizCategory=" + this.getBizCategory() + ")";
    }
}
