// Generated by delombok at Wed Apr 13 12:12:31 CST 2022
package com.puboot.module.admin.model;

import com.puboot.module.admin.vo.base.BaseVo;

/**
 * @author Linzhaoguan
 * @version V1.0
 * @date 2019年9月11日
 */
public class BizArticleTags extends BaseVo {
    private static final long serialVersionUID = 2627147974506469978L;
    private Integer tagId;
    private Integer articleId;

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof BizArticleTags)) return false;
        final BizArticleTags other = (BizArticleTags) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (!super.equals(o)) return false;
        final java.lang.Object this$tagId = this.getTagId();
        final java.lang.Object other$tagId = other.getTagId();
        if (this$tagId == null ? other$tagId != null : !this$tagId.equals(other$tagId)) return false;
        final java.lang.Object this$articleId = this.getArticleId();
        final java.lang.Object other$articleId = other.getArticleId();
        if (this$articleId == null ? other$articleId != null : !this$articleId.equals(other$articleId)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof BizArticleTags;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = super.hashCode();
        final java.lang.Object $tagId = this.getTagId();
        result = result * PRIME + ($tagId == null ? 43 : $tagId.hashCode());
        final java.lang.Object $articleId = this.getArticleId();
        result = result * PRIME + ($articleId == null ? 43 : $articleId.hashCode());
        return result;
    }

    @java.lang.SuppressWarnings("all")
    public BizArticleTags() {
    }

    @java.lang.SuppressWarnings("all")
    public Integer getTagId() {
        return this.tagId;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getArticleId() {
        return this.articleId;
    }

    @java.lang.SuppressWarnings("all")
    public void setTagId(final Integer tagId) {
        this.tagId = tagId;
    }

    @java.lang.SuppressWarnings("all")
    public void setArticleId(final Integer articleId) {
        this.articleId = articleId;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "BizArticleTags(tagId=" + this.getTagId() + ", articleId=" + this.getArticleId() + ")";
    }
}
