// Generated by delombok at Wed Apr 13 12:12:31 CST 2022
package com.puboot.module.admin.model;

import com.puboot.module.admin.vo.base.BaseVo;
import java.util.Date;

/**
 * @author Linzhaoguan
 * @version V1.0
 * @date 2019年9月11日
 */
public class BizArticleLook extends BaseVo {
    private static final long serialVersionUID = 1052723347580827581L;
    private Integer articleId;
    private String userId;
    private String userIp;
    private Date lookTime;

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof BizArticleLook)) return false;
        final BizArticleLook other = (BizArticleLook) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (!super.equals(o)) return false;
        final java.lang.Object this$articleId = this.getArticleId();
        final java.lang.Object other$articleId = other.getArticleId();
        if (this$articleId == null ? other$articleId != null : !this$articleId.equals(other$articleId)) return false;
        final java.lang.Object this$userId = this.getUserId();
        final java.lang.Object other$userId = other.getUserId();
        if (this$userId == null ? other$userId != null : !this$userId.equals(other$userId)) return false;
        final java.lang.Object this$userIp = this.getUserIp();
        final java.lang.Object other$userIp = other.getUserIp();
        if (this$userIp == null ? other$userIp != null : !this$userIp.equals(other$userIp)) return false;
        final java.lang.Object this$lookTime = this.getLookTime();
        final java.lang.Object other$lookTime = other.getLookTime();
        if (this$lookTime == null ? other$lookTime != null : !this$lookTime.equals(other$lookTime)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof BizArticleLook;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = super.hashCode();
        final java.lang.Object $articleId = this.getArticleId();
        result = result * PRIME + ($articleId == null ? 43 : $articleId.hashCode());
        final java.lang.Object $userId = this.getUserId();
        result = result * PRIME + ($userId == null ? 43 : $userId.hashCode());
        final java.lang.Object $userIp = this.getUserIp();
        result = result * PRIME + ($userIp == null ? 43 : $userIp.hashCode());
        final java.lang.Object $lookTime = this.getLookTime();
        result = result * PRIME + ($lookTime == null ? 43 : $lookTime.hashCode());
        return result;
    }

    @java.lang.SuppressWarnings("all")
    public BizArticleLook() {
    }

    @java.lang.SuppressWarnings("all")
    public Integer getArticleId() {
        return this.articleId;
    }

    @java.lang.SuppressWarnings("all")
    public String getUserId() {
        return this.userId;
    }

    @java.lang.SuppressWarnings("all")
    public String getUserIp() {
        return this.userIp;
    }

    @java.lang.SuppressWarnings("all")
    public Date getLookTime() {
        return this.lookTime;
    }

    @java.lang.SuppressWarnings("all")
    public void setArticleId(final Integer articleId) {
        this.articleId = articleId;
    }

    @java.lang.SuppressWarnings("all")
    public void setUserId(final String userId) {
        this.userId = userId;
    }

    @java.lang.SuppressWarnings("all")
    public void setUserIp(final String userIp) {
        this.userIp = userIp;
    }

    @java.lang.SuppressWarnings("all")
    public void setLookTime(final Date lookTime) {
        this.lookTime = lookTime;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "BizArticleLook(articleId=" + this.getArticleId() + ", userId=" + this.getUserId() + ", userIp=" + this.getUserIp() + ", lookTime=" + this.getLookTime() + ")";
    }
}
