// Generated by delombok at Wed Apr 13 12:12:31 CST 2022
package com.puboot.module.admin.model;

import com.baomidou.mybatisplus.annotation.TableField;
import com.puboot.module.admin.vo.base.BaseVo;

/**
 * @author Linzhaoguan
 * @version V1.0
 * @date 2019年9月11日
 */
public class BizComment extends BaseVo {
    private static final long serialVersionUID = -7221371985694751121L;
    private String userId;
    private Integer sid;
    private Integer pid;
    private String qq;
    private String nickname;
    private String avatar;
    private String email;
    private String url;
    private Integer status;
    private String ip;
    private String lng;
    private String lat;
    private String address;
    private String os;
    private String osShortName;
    private String browser;
    private String browserShortName;
    private String content;
    private String remark;
    private Integer support;
    private Integer oppose;
    @TableField(exist = false)
    private Integer loveCount;
    @TableField(exist = false)
    BizComment parent;
    @TableField(exist = false)
    BizArticle article;

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof BizComment)) return false;
        final BizComment other = (BizComment) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (!super.equals(o)) return false;
        final java.lang.Object this$userId = this.getUserId();
        final java.lang.Object other$userId = other.getUserId();
        if (this$userId == null ? other$userId != null : !this$userId.equals(other$userId)) return false;
        final java.lang.Object this$sid = this.getSid();
        final java.lang.Object other$sid = other.getSid();
        if (this$sid == null ? other$sid != null : !this$sid.equals(other$sid)) return false;
        final java.lang.Object this$pid = this.getPid();
        final java.lang.Object other$pid = other.getPid();
        if (this$pid == null ? other$pid != null : !this$pid.equals(other$pid)) return false;
        final java.lang.Object this$qq = this.getQq();
        final java.lang.Object other$qq = other.getQq();
        if (this$qq == null ? other$qq != null : !this$qq.equals(other$qq)) return false;
        final java.lang.Object this$nickname = this.getNickname();
        final java.lang.Object other$nickname = other.getNickname();
        if (this$nickname == null ? other$nickname != null : !this$nickname.equals(other$nickname)) return false;
        final java.lang.Object this$avatar = this.getAvatar();
        final java.lang.Object other$avatar = other.getAvatar();
        if (this$avatar == null ? other$avatar != null : !this$avatar.equals(other$avatar)) return false;
        final java.lang.Object this$email = this.getEmail();
        final java.lang.Object other$email = other.getEmail();
        if (this$email == null ? other$email != null : !this$email.equals(other$email)) return false;
        final java.lang.Object this$url = this.getUrl();
        final java.lang.Object other$url = other.getUrl();
        if (this$url == null ? other$url != null : !this$url.equals(other$url)) return false;
        final java.lang.Object this$status = this.getStatus();
        final java.lang.Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
        final java.lang.Object this$ip = this.getIp();
        final java.lang.Object other$ip = other.getIp();
        if (this$ip == null ? other$ip != null : !this$ip.equals(other$ip)) return false;
        final java.lang.Object this$lng = this.getLng();
        final java.lang.Object other$lng = other.getLng();
        if (this$lng == null ? other$lng != null : !this$lng.equals(other$lng)) return false;
        final java.lang.Object this$lat = this.getLat();
        final java.lang.Object other$lat = other.getLat();
        if (this$lat == null ? other$lat != null : !this$lat.equals(other$lat)) return false;
        final java.lang.Object this$address = this.getAddress();
        final java.lang.Object other$address = other.getAddress();
        if (this$address == null ? other$address != null : !this$address.equals(other$address)) return false;
        final java.lang.Object this$os = this.getOs();
        final java.lang.Object other$os = other.getOs();
        if (this$os == null ? other$os != null : !this$os.equals(other$os)) return false;
        final java.lang.Object this$osShortName = this.getOsShortName();
        final java.lang.Object other$osShortName = other.getOsShortName();
        if (this$osShortName == null ? other$osShortName != null : !this$osShortName.equals(other$osShortName)) return false;
        final java.lang.Object this$browser = this.getBrowser();
        final java.lang.Object other$browser = other.getBrowser();
        if (this$browser == null ? other$browser != null : !this$browser.equals(other$browser)) return false;
        final java.lang.Object this$browserShortName = this.getBrowserShortName();
        final java.lang.Object other$browserShortName = other.getBrowserShortName();
        if (this$browserShortName == null ? other$browserShortName != null : !this$browserShortName.equals(other$browserShortName)) return false;
        final java.lang.Object this$content = this.getContent();
        final java.lang.Object other$content = other.getContent();
        if (this$content == null ? other$content != null : !this$content.equals(other$content)) return false;
        final java.lang.Object this$remark = this.getRemark();
        final java.lang.Object other$remark = other.getRemark();
        if (this$remark == null ? other$remark != null : !this$remark.equals(other$remark)) return false;
        final java.lang.Object this$support = this.getSupport();
        final java.lang.Object other$support = other.getSupport();
        if (this$support == null ? other$support != null : !this$support.equals(other$support)) return false;
        final java.lang.Object this$oppose = this.getOppose();
        final java.lang.Object other$oppose = other.getOppose();
        if (this$oppose == null ? other$oppose != null : !this$oppose.equals(other$oppose)) return false;
        final java.lang.Object this$loveCount = this.getLoveCount();
        final java.lang.Object other$loveCount = other.getLoveCount();
        if (this$loveCount == null ? other$loveCount != null : !this$loveCount.equals(other$loveCount)) return false;
        final java.lang.Object this$parent = this.getParent();
        final java.lang.Object other$parent = other.getParent();
        if (this$parent == null ? other$parent != null : !this$parent.equals(other$parent)) return false;
        final java.lang.Object this$article = this.getArticle();
        final java.lang.Object other$article = other.getArticle();
        if (this$article == null ? other$article != null : !this$article.equals(other$article)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof BizComment;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = super.hashCode();
        final java.lang.Object $userId = this.getUserId();
        result = result * PRIME + ($userId == null ? 43 : $userId.hashCode());
        final java.lang.Object $sid = this.getSid();
        result = result * PRIME + ($sid == null ? 43 : $sid.hashCode());
        final java.lang.Object $pid = this.getPid();
        result = result * PRIME + ($pid == null ? 43 : $pid.hashCode());
        final java.lang.Object $qq = this.getQq();
        result = result * PRIME + ($qq == null ? 43 : $qq.hashCode());
        final java.lang.Object $nickname = this.getNickname();
        result = result * PRIME + ($nickname == null ? 43 : $nickname.hashCode());
        final java.lang.Object $avatar = this.getAvatar();
        result = result * PRIME + ($avatar == null ? 43 : $avatar.hashCode());
        final java.lang.Object $email = this.getEmail();
        result = result * PRIME + ($email == null ? 43 : $email.hashCode());
        final java.lang.Object $url = this.getUrl();
        result = result * PRIME + ($url == null ? 43 : $url.hashCode());
        final java.lang.Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        final java.lang.Object $ip = this.getIp();
        result = result * PRIME + ($ip == null ? 43 : $ip.hashCode());
        final java.lang.Object $lng = this.getLng();
        result = result * PRIME + ($lng == null ? 43 : $lng.hashCode());
        final java.lang.Object $lat = this.getLat();
        result = result * PRIME + ($lat == null ? 43 : $lat.hashCode());
        final java.lang.Object $address = this.getAddress();
        result = result * PRIME + ($address == null ? 43 : $address.hashCode());
        final java.lang.Object $os = this.getOs();
        result = result * PRIME + ($os == null ? 43 : $os.hashCode());
        final java.lang.Object $osShortName = this.getOsShortName();
        result = result * PRIME + ($osShortName == null ? 43 : $osShortName.hashCode());
        final java.lang.Object $browser = this.getBrowser();
        result = result * PRIME + ($browser == null ? 43 : $browser.hashCode());
        final java.lang.Object $browserShortName = this.getBrowserShortName();
        result = result * PRIME + ($browserShortName == null ? 43 : $browserShortName.hashCode());
        final java.lang.Object $content = this.getContent();
        result = result * PRIME + ($content == null ? 43 : $content.hashCode());
        final java.lang.Object $remark = this.getRemark();
        result = result * PRIME + ($remark == null ? 43 : $remark.hashCode());
        final java.lang.Object $support = this.getSupport();
        result = result * PRIME + ($support == null ? 43 : $support.hashCode());
        final java.lang.Object $oppose = this.getOppose();
        result = result * PRIME + ($oppose == null ? 43 : $oppose.hashCode());
        final java.lang.Object $loveCount = this.getLoveCount();
        result = result * PRIME + ($loveCount == null ? 43 : $loveCount.hashCode());
        final java.lang.Object $parent = this.getParent();
        result = result * PRIME + ($parent == null ? 43 : $parent.hashCode());
        final java.lang.Object $article = this.getArticle();
        result = result * PRIME + ($article == null ? 43 : $article.hashCode());
        return result;
    }

    @java.lang.SuppressWarnings("all")
    public BizComment() {
    }

    @java.lang.SuppressWarnings("all")
    public String getUserId() {
        return this.userId;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getSid() {
        return this.sid;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getPid() {
        return this.pid;
    }

    @java.lang.SuppressWarnings("all")
    public String getQq() {
        return this.qq;
    }

    @java.lang.SuppressWarnings("all")
    public String getNickname() {
        return this.nickname;
    }

    @java.lang.SuppressWarnings("all")
    public String getAvatar() {
        return this.avatar;
    }

    @java.lang.SuppressWarnings("all")
    public String getEmail() {
        return this.email;
    }

    @java.lang.SuppressWarnings("all")
    public String getUrl() {
        return this.url;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    public String getIp() {
        return this.ip;
    }

    @java.lang.SuppressWarnings("all")
    public String getLng() {
        return this.lng;
    }

    @java.lang.SuppressWarnings("all")
    public String getLat() {
        return this.lat;
    }

    @java.lang.SuppressWarnings("all")
    public String getAddress() {
        return this.address;
    }

    @java.lang.SuppressWarnings("all")
    public String getOs() {
        return this.os;
    }

    @java.lang.SuppressWarnings("all")
    public String getOsShortName() {
        return this.osShortName;
    }

    @java.lang.SuppressWarnings("all")
    public String getBrowser() {
        return this.browser;
    }

    @java.lang.SuppressWarnings("all")
    public String getBrowserShortName() {
        return this.browserShortName;
    }

    @java.lang.SuppressWarnings("all")
    public String getContent() {
        return this.content;
    }

    @java.lang.SuppressWarnings("all")
    public String getRemark() {
        return this.remark;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getSupport() {
        return this.support;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getOppose() {
        return this.oppose;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getLoveCount() {
        return this.loveCount;
    }

    @java.lang.SuppressWarnings("all")
    public BizComment getParent() {
        return this.parent;
    }

    @java.lang.SuppressWarnings("all")
    public BizArticle getArticle() {
        return this.article;
    }

    @java.lang.SuppressWarnings("all")
    public void setUserId(final String userId) {
        this.userId = userId;
    }

    @java.lang.SuppressWarnings("all")
    public void setSid(final Integer sid) {
        this.sid = sid;
    }

    @java.lang.SuppressWarnings("all")
    public void setPid(final Integer pid) {
        this.pid = pid;
    }

    @java.lang.SuppressWarnings("all")
    public void setQq(final String qq) {
        this.qq = qq;
    }

    @java.lang.SuppressWarnings("all")
    public void setNickname(final String nickname) {
        this.nickname = nickname;
    }

    @java.lang.SuppressWarnings("all")
    public void setAvatar(final String avatar) {
        this.avatar = avatar;
    }

    @java.lang.SuppressWarnings("all")
    public void setEmail(final String email) {
        this.email = email;
    }

    @java.lang.SuppressWarnings("all")
    public void setUrl(final String url) {
        this.url = url;
    }

    @java.lang.SuppressWarnings("all")
    public void setStatus(final Integer status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    public void setIp(final String ip) {
        this.ip = ip;
    }

    @java.lang.SuppressWarnings("all")
    public void setLng(final String lng) {
        this.lng = lng;
    }

    @java.lang.SuppressWarnings("all")
    public void setLat(final String lat) {
        this.lat = lat;
    }

    @java.lang.SuppressWarnings("all")
    public void setAddress(final String address) {
        this.address = address;
    }

    @java.lang.SuppressWarnings("all")
    public void setOs(final String os) {
        this.os = os;
    }

    @java.lang.SuppressWarnings("all")
    public void setOsShortName(final String osShortName) {
        this.osShortName = osShortName;
    }

    @java.lang.SuppressWarnings("all")
    public void setBrowser(final String browser) {
        this.browser = browser;
    }

    @java.lang.SuppressWarnings("all")
    public void setBrowserShortName(final String browserShortName) {
        this.browserShortName = browserShortName;
    }

    @java.lang.SuppressWarnings("all")
    public void setContent(final String content) {
        this.content = content;
    }

    @java.lang.SuppressWarnings("all")
    public void setRemark(final String remark) {
        this.remark = remark;
    }

    @java.lang.SuppressWarnings("all")
    public void setSupport(final Integer support) {
        this.support = support;
    }

    @java.lang.SuppressWarnings("all")
    public void setOppose(final Integer oppose) {
        this.oppose = oppose;
    }

    @java.lang.SuppressWarnings("all")
    public void setLoveCount(final Integer loveCount) {
        this.loveCount = loveCount;
    }

    @java.lang.SuppressWarnings("all")
    public void setParent(final BizComment parent) {
        this.parent = parent;
    }

    @java.lang.SuppressWarnings("all")
    public void setArticle(final BizArticle article) {
        this.article = article;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "BizComment(userId=" + this.getUserId() + ", sid=" + this.getSid() + ", pid=" + this.getPid() + ", qq=" + this.getQq() + ", nickname=" + this.getNickname() + ", avatar=" + this.getAvatar() + ", email=" + this.getEmail() + ", url=" + this.getUrl() + ", status=" + this.getStatus() + ", ip=" + this.getIp() + ", lng=" + this.getLng() + ", lat=" + this.getLat() + ", address=" + this.getAddress() + ", os=" + this.getOs() + ", osShortName=" + this.getOsShortName() + ", browser=" + this.getBrowser() + ", browserShortName=" + this.getBrowserShortName() + ", content=" + this.getContent() + ", remark=" + this.getRemark() + ", support=" + this.getSupport() + ", oppose=" + this.getOppose() + ", loveCount=" + this.getLoveCount() + ", parent=" + this.getParent() + ", article=" + this.getArticle() + ")";
    }
}
