// Generated by delombok at Wed Apr 13 12:12:31 CST 2022
package com.puboot.module.admin.model;

import com.puboot.module.admin.vo.base.BaseVo;

/**
 * @author Linzhaoguan
 * @version V1.0
 * @date 2019年9月11日
 */
public class BizLove extends BaseVo {
    private static final long serialVersionUID = 6825108677279625433L;
    private Integer bizId;
    private Integer bizType;
    private String userId;
    private String userIp;
    private Integer status;

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof BizLove)) return false;
        final BizLove other = (BizLove) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (!super.equals(o)) return false;
        final java.lang.Object this$bizId = this.getBizId();
        final java.lang.Object other$bizId = other.getBizId();
        if (this$bizId == null ? other$bizId != null : !this$bizId.equals(other$bizId)) return false;
        final java.lang.Object this$bizType = this.getBizType();
        final java.lang.Object other$bizType = other.getBizType();
        if (this$bizType == null ? other$bizType != null : !this$bizType.equals(other$bizType)) return false;
        final java.lang.Object this$userId = this.getUserId();
        final java.lang.Object other$userId = other.getUserId();
        if (this$userId == null ? other$userId != null : !this$userId.equals(other$userId)) return false;
        final java.lang.Object this$userIp = this.getUserIp();
        final java.lang.Object other$userIp = other.getUserIp();
        if (this$userIp == null ? other$userIp != null : !this$userIp.equals(other$userIp)) return false;
        final java.lang.Object this$status = this.getStatus();
        final java.lang.Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof BizLove;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = super.hashCode();
        final java.lang.Object $bizId = this.getBizId();
        result = result * PRIME + ($bizId == null ? 43 : $bizId.hashCode());
        final java.lang.Object $bizType = this.getBizType();
        result = result * PRIME + ($bizType == null ? 43 : $bizType.hashCode());
        final java.lang.Object $userId = this.getUserId();
        result = result * PRIME + ($userId == null ? 43 : $userId.hashCode());
        final java.lang.Object $userIp = this.getUserIp();
        result = result * PRIME + ($userIp == null ? 43 : $userIp.hashCode());
        final java.lang.Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        return result;
    }

    @java.lang.SuppressWarnings("all")
    public BizLove() {
    }

    @java.lang.SuppressWarnings("all")
    public Integer getBizId() {
        return this.bizId;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getBizType() {
        return this.bizType;
    }

    @java.lang.SuppressWarnings("all")
    public String getUserId() {
        return this.userId;
    }

    @java.lang.SuppressWarnings("all")
    public String getUserIp() {
        return this.userIp;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    public void setBizId(final Integer bizId) {
        this.bizId = bizId;
    }

    @java.lang.SuppressWarnings("all")
    public void setBizType(final Integer bizType) {
        this.bizType = bizType;
    }

    @java.lang.SuppressWarnings("all")
    public void setUserId(final String userId) {
        this.userId = userId;
    }

    @java.lang.SuppressWarnings("all")
    public void setUserIp(final String userIp) {
        this.userIp = userIp;
    }

    @java.lang.SuppressWarnings("all")
    public void setStatus(final Integer status) {
        this.status = status;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "BizLove(bizId=" + this.getBizId() + ", bizType=" + this.getBizType() + ", userId=" + this.getUserId() + ", userIp=" + this.getUserIp() + ", status=" + this.getStatus() + ")";
    }
}
