// Generated by delombok at Wed Apr 13 12:12:31 CST 2022
package com.puboot.module.admin.model;

import com.puboot.module.admin.vo.base.BaseVo;

/**
 * @author Linzhaoguan
 * @version V1.0
 * @date 2019年9月11日
 */
public class BizLink extends BaseVo {
    private static final long serialVersionUID = -6511423333796987519L;
    private String url;
    private String name;
    private String description;
    private String img;
    private String email;
    private String qq;
    private Integer status;
    private Integer origin;
    private String remark;

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof BizLink)) return false;
        final BizLink other = (BizLink) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (!super.equals(o)) return false;
        final java.lang.Object this$url = this.getUrl();
        final java.lang.Object other$url = other.getUrl();
        if (this$url == null ? other$url != null : !this$url.equals(other$url)) return false;
        final java.lang.Object this$name = this.getName();
        final java.lang.Object other$name = other.getName();
        if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
        final java.lang.Object this$description = this.getDescription();
        final java.lang.Object other$description = other.getDescription();
        if (this$description == null ? other$description != null : !this$description.equals(other$description)) return false;
        final java.lang.Object this$img = this.getImg();
        final java.lang.Object other$img = other.getImg();
        if (this$img == null ? other$img != null : !this$img.equals(other$img)) return false;
        final java.lang.Object this$email = this.getEmail();
        final java.lang.Object other$email = other.getEmail();
        if (this$email == null ? other$email != null : !this$email.equals(other$email)) return false;
        final java.lang.Object this$qq = this.getQq();
        final java.lang.Object other$qq = other.getQq();
        if (this$qq == null ? other$qq != null : !this$qq.equals(other$qq)) return false;
        final java.lang.Object this$status = this.getStatus();
        final java.lang.Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
        final java.lang.Object this$origin = this.getOrigin();
        final java.lang.Object other$origin = other.getOrigin();
        if (this$origin == null ? other$origin != null : !this$origin.equals(other$origin)) return false;
        final java.lang.Object this$remark = this.getRemark();
        final java.lang.Object other$remark = other.getRemark();
        if (this$remark == null ? other$remark != null : !this$remark.equals(other$remark)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof BizLink;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = super.hashCode();
        final java.lang.Object $url = this.getUrl();
        result = result * PRIME + ($url == null ? 43 : $url.hashCode());
        final java.lang.Object $name = this.getName();
        result = result * PRIME + ($name == null ? 43 : $name.hashCode());
        final java.lang.Object $description = this.getDescription();
        result = result * PRIME + ($description == null ? 43 : $description.hashCode());
        final java.lang.Object $img = this.getImg();
        result = result * PRIME + ($img == null ? 43 : $img.hashCode());
        final java.lang.Object $email = this.getEmail();
        result = result * PRIME + ($email == null ? 43 : $email.hashCode());
        final java.lang.Object $qq = this.getQq();
        result = result * PRIME + ($qq == null ? 43 : $qq.hashCode());
        final java.lang.Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        final java.lang.Object $origin = this.getOrigin();
        result = result * PRIME + ($origin == null ? 43 : $origin.hashCode());
        final java.lang.Object $remark = this.getRemark();
        result = result * PRIME + ($remark == null ? 43 : $remark.hashCode());
        return result;
    }

    @java.lang.SuppressWarnings("all")
    public BizLink() {
    }

    @java.lang.SuppressWarnings("all")
    public String getUrl() {
        return this.url;
    }

    @java.lang.SuppressWarnings("all")
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    public String getDescription() {
        return this.description;
    }

    @java.lang.SuppressWarnings("all")
    public String getImg() {
        return this.img;
    }

    @java.lang.SuppressWarnings("all")
    public String getEmail() {
        return this.email;
    }

    @java.lang.SuppressWarnings("all")
    public String getQq() {
        return this.qq;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getOrigin() {
        return this.origin;
    }

    @java.lang.SuppressWarnings("all")
    public String getRemark() {
        return this.remark;
    }

    @java.lang.SuppressWarnings("all")
    public BizLink setUrl(final String url) {
        this.url = url;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public BizLink setName(final String name) {
        this.name = name;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public BizLink setDescription(final String description) {
        this.description = description;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public BizLink setImg(final String img) {
        this.img = img;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public BizLink setEmail(final String email) {
        this.email = email;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public BizLink setQq(final String qq) {
        this.qq = qq;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public BizLink setStatus(final Integer status) {
        this.status = status;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public BizLink setOrigin(final Integer origin) {
        this.origin = origin;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public BizLink setRemark(final String remark) {
        this.remark = remark;
        return this;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "BizLink(url=" + this.getUrl() + ", name=" + this.getName() + ", description=" + this.getDescription() + ", img=" + this.getImg() + ", email=" + this.getEmail() + ", qq=" + this.getQq() + ", status=" + this.getStatus() + ", origin=" + this.getOrigin() + ", remark=" + this.getRemark() + ")";
    }
}
