// Generated by delombok at Wed Apr 13 12:12:31 CST 2022
package com.puboot.module.admin.model;

import com.baomidou.mybatisplus.annotation.TableField;
import java.io.Serializable;
import java.util.Date;
import java.util.List;

/**
 * @author Linzhaoguan
 * @version V1.0
 * @date 2019年9月11日
 */
public class Permission implements Serializable {
    private static final long serialVersionUID = -4317225965160245362L;
    private Integer id;
    /**
     * 权限id
     */
    private String permissionId;
    /**
     * 权限名称
     */
    private String name;
    /**
     * 权限描述
     */
    private String description;
    /**
     * 权限访问路径
     */
    private String url;
    /**
     * 权限标识
     */
    private String perms;
    /**
     * 父级权限id
     */
    private Integer parentId;
    /**
     * 类型   0：目录   1：菜单   2：按钮
     */
    private Integer type;
    /**
     * 排序
     */
    private Integer orderNum;
    /**
     * 图标
     */
    private String icon;
    /**
     * 状态：1有效; 0无效
     */
    private Integer status;
    private Date createTime;
    private Date updateTime;
    @TableField(exist = false)
    private List<Permission> children;

    @java.lang.SuppressWarnings("all")
    public Permission() {
    }

    @java.lang.SuppressWarnings("all")
    public Integer getId() {
        return this.id;
    }

    /**
     * 权限id
     */
    @java.lang.SuppressWarnings("all")
    public String getPermissionId() {
        return this.permissionId;
    }

    /**
     * 权限名称
     */
    @java.lang.SuppressWarnings("all")
    public String getName() {
        return this.name;
    }

    /**
     * 权限描述
     */
    @java.lang.SuppressWarnings("all")
    public String getDescription() {
        return this.description;
    }

    /**
     * 权限访问路径
     */
    @java.lang.SuppressWarnings("all")
    public String getUrl() {
        return this.url;
    }

    /**
     * 权限标识
     */
    @java.lang.SuppressWarnings("all")
    public String getPerms() {
        return this.perms;
    }

    /**
     * 父级权限id
     */
    @java.lang.SuppressWarnings("all")
    public Integer getParentId() {
        return this.parentId;
    }

    /**
     * 类型   0：目录   1：菜单   2：按钮
     */
    @java.lang.SuppressWarnings("all")
    public Integer getType() {
        return this.type;
    }

    /**
     * 排序
     */
    @java.lang.SuppressWarnings("all")
    public Integer getOrderNum() {
        return this.orderNum;
    }

    /**
     * 图标
     */
    @java.lang.SuppressWarnings("all")
    public String getIcon() {
        return this.icon;
    }

    /**
     * 状态：1有效; 0无效
     */
    @java.lang.SuppressWarnings("all")
    public Integer getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    public Date getCreateTime() {
        return this.createTime;
    }

    @java.lang.SuppressWarnings("all")
    public Date getUpdateTime() {
        return this.updateTime;
    }

    @java.lang.SuppressWarnings("all")
    public List<Permission> getChildren() {
        return this.children;
    }

    @java.lang.SuppressWarnings("all")
    public Permission setId(final Integer id) {
        this.id = id;
        return this;
    }

    /**
     * 权限id
     * @return this
     */
    @java.lang.SuppressWarnings("all")
    public Permission setPermissionId(final String permissionId) {
        this.permissionId = permissionId;
        return this;
    }

    /**
     * 权限名称
     * @return this
     */
    @java.lang.SuppressWarnings("all")
    public Permission setName(final String name) {
        this.name = name;
        return this;
    }

    /**
     * 权限描述
     * @return this
     */
    @java.lang.SuppressWarnings("all")
    public Permission setDescription(final String description) {
        this.description = description;
        return this;
    }

    /**
     * 权限访问路径
     * @return this
     */
    @java.lang.SuppressWarnings("all")
    public Permission setUrl(final String url) {
        this.url = url;
        return this;
    }

    /**
     * 权限标识
     * @return this
     */
    @java.lang.SuppressWarnings("all")
    public Permission setPerms(final String perms) {
        this.perms = perms;
        return this;
    }

    /**
     * 父级权限id
     * @return this
     */
    @java.lang.SuppressWarnings("all")
    public Permission setParentId(final Integer parentId) {
        this.parentId = parentId;
        return this;
    }

    /**
     * 类型   0：目录   1：菜单   2：按钮
     * @return this
     */
    @java.lang.SuppressWarnings("all")
    public Permission setType(final Integer type) {
        this.type = type;
        return this;
    }

    /**
     * 排序
     * @return this
     */
    @java.lang.SuppressWarnings("all")
    public Permission setOrderNum(final Integer orderNum) {
        this.orderNum = orderNum;
        return this;
    }

    /**
     * 图标
     * @return this
     */
    @java.lang.SuppressWarnings("all")
    public Permission setIcon(final String icon) {
        this.icon = icon;
        return this;
    }

    /**
     * 状态：1有效; 0无效
     * @return this
     */
    @java.lang.SuppressWarnings("all")
    public Permission setStatus(final Integer status) {
        this.status = status;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public Permission setCreateTime(final Date createTime) {
        this.createTime = createTime;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public Permission setUpdateTime(final Date updateTime) {
        this.updateTime = updateTime;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public Permission setChildren(final List<Permission> children) {
        this.children = children;
        return this;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Permission)) return false;
        final Permission other = (Permission) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$permissionId = this.getPermissionId();
        final java.lang.Object other$permissionId = other.getPermissionId();
        if (this$permissionId == null ? other$permissionId != null : !this$permissionId.equals(other$permissionId)) return false;
        final java.lang.Object this$name = this.getName();
        final java.lang.Object other$name = other.getName();
        if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
        final java.lang.Object this$description = this.getDescription();
        final java.lang.Object other$description = other.getDescription();
        if (this$description == null ? other$description != null : !this$description.equals(other$description)) return false;
        final java.lang.Object this$url = this.getUrl();
        final java.lang.Object other$url = other.getUrl();
        if (this$url == null ? other$url != null : !this$url.equals(other$url)) return false;
        final java.lang.Object this$perms = this.getPerms();
        final java.lang.Object other$perms = other.getPerms();
        if (this$perms == null ? other$perms != null : !this$perms.equals(other$perms)) return false;
        final java.lang.Object this$parentId = this.getParentId();
        final java.lang.Object other$parentId = other.getParentId();
        if (this$parentId == null ? other$parentId != null : !this$parentId.equals(other$parentId)) return false;
        final java.lang.Object this$type = this.getType();
        final java.lang.Object other$type = other.getType();
        if (this$type == null ? other$type != null : !this$type.equals(other$type)) return false;
        final java.lang.Object this$orderNum = this.getOrderNum();
        final java.lang.Object other$orderNum = other.getOrderNum();
        if (this$orderNum == null ? other$orderNum != null : !this$orderNum.equals(other$orderNum)) return false;
        final java.lang.Object this$icon = this.getIcon();
        final java.lang.Object other$icon = other.getIcon();
        if (this$icon == null ? other$icon != null : !this$icon.equals(other$icon)) return false;
        final java.lang.Object this$status = this.getStatus();
        final java.lang.Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
        final java.lang.Object this$createTime = this.getCreateTime();
        final java.lang.Object other$createTime = other.getCreateTime();
        if (this$createTime == null ? other$createTime != null : !this$createTime.equals(other$createTime)) return false;
        final java.lang.Object this$updateTime = this.getUpdateTime();
        final java.lang.Object other$updateTime = other.getUpdateTime();
        if (this$updateTime == null ? other$updateTime != null : !this$updateTime.equals(other$updateTime)) return false;
        final java.lang.Object this$children = this.getChildren();
        final java.lang.Object other$children = other.getChildren();
        if (this$children == null ? other$children != null : !this$children.equals(other$children)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Permission;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $permissionId = this.getPermissionId();
        result = result * PRIME + ($permissionId == null ? 43 : $permissionId.hashCode());
        final java.lang.Object $name = this.getName();
        result = result * PRIME + ($name == null ? 43 : $name.hashCode());
        final java.lang.Object $description = this.getDescription();
        result = result * PRIME + ($description == null ? 43 : $description.hashCode());
        final java.lang.Object $url = this.getUrl();
        result = result * PRIME + ($url == null ? 43 : $url.hashCode());
        final java.lang.Object $perms = this.getPerms();
        result = result * PRIME + ($perms == null ? 43 : $perms.hashCode());
        final java.lang.Object $parentId = this.getParentId();
        result = result * PRIME + ($parentId == null ? 43 : $parentId.hashCode());
        final java.lang.Object $type = this.getType();
        result = result * PRIME + ($type == null ? 43 : $type.hashCode());
        final java.lang.Object $orderNum = this.getOrderNum();
        result = result * PRIME + ($orderNum == null ? 43 : $orderNum.hashCode());
        final java.lang.Object $icon = this.getIcon();
        result = result * PRIME + ($icon == null ? 43 : $icon.hashCode());
        final java.lang.Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        final java.lang.Object $createTime = this.getCreateTime();
        result = result * PRIME + ($createTime == null ? 43 : $createTime.hashCode());
        final java.lang.Object $updateTime = this.getUpdateTime();
        result = result * PRIME + ($updateTime == null ? 43 : $updateTime.hashCode());
        final java.lang.Object $children = this.getChildren();
        result = result * PRIME + ($children == null ? 43 : $children.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "Permission(id=" + this.getId() + ", permissionId=" + this.getPermissionId() + ", name=" + this.getName() + ", description=" + this.getDescription() + ", url=" + this.getUrl() + ", perms=" + this.getPerms() + ", parentId=" + this.getParentId() + ", type=" + this.getType() + ", orderNum=" + this.getOrderNum() + ", icon=" + this.getIcon() + ", status=" + this.getStatus() + ", createTime=" + this.getCreateTime() + ", updateTime=" + this.getUpdateTime() + ", children=" + this.getChildren() + ")";
    }
}
