// Generated by delombok at Wed Apr 13 12:12:31 CST 2022
package com.puboot.module.admin.model;

import java.io.Serializable;

/**
 * @author Linzhaoguan
 * @version V1.0
 * @date 2019年9月11日
 */
public class RolePermission implements Serializable {
    private static final long serialVersionUID = -902800328539403089L;
    private Integer id;
    /**
     * 角色id
     */
    private String roleId;
    /**
     * 权限id
     */
    private String permissionId;

    @java.lang.SuppressWarnings("all")
    public RolePermission() {
    }

    @java.lang.SuppressWarnings("all")
    public Integer getId() {
        return this.id;
    }

    /**
     * 角色id
     */
    @java.lang.SuppressWarnings("all")
    public String getRoleId() {
        return this.roleId;
    }

    /**
     * 权限id
     */
    @java.lang.SuppressWarnings("all")
    public String getPermissionId() {
        return this.permissionId;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Integer id) {
        this.id = id;
    }

    /**
     * 角色id
     */
    @java.lang.SuppressWarnings("all")
    public void setRoleId(final String roleId) {
        this.roleId = roleId;
    }

    /**
     * 权限id
     */
    @java.lang.SuppressWarnings("all")
    public void setPermissionId(final String permissionId) {
        this.permissionId = permissionId;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof RolePermission)) return false;
        final RolePermission other = (RolePermission) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$roleId = this.getRoleId();
        final java.lang.Object other$roleId = other.getRoleId();
        if (this$roleId == null ? other$roleId != null : !this$roleId.equals(other$roleId)) return false;
        final java.lang.Object this$permissionId = this.getPermissionId();
        final java.lang.Object other$permissionId = other.getPermissionId();
        if (this$permissionId == null ? other$permissionId != null : !this$permissionId.equals(other$permissionId)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof RolePermission;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $roleId = this.getRoleId();
        result = result * PRIME + ($roleId == null ? 43 : $roleId.hashCode());
        final java.lang.Object $permissionId = this.getPermissionId();
        result = result * PRIME + ($permissionId == null ? 43 : $permissionId.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "RolePermission(id=" + this.getId() + ", roleId=" + this.getRoleId() + ", permissionId=" + this.getPermissionId() + ")";
    }
}
