// Generated by delombok at Wed Apr 13 12:12:31 CST 2022
package com.puboot.module.admin.model;

import java.io.Serializable;

/**
 * @author Linzhaoguan
 * @version V1.0
 * @date 2019年9月11日
 */
public class SysConfig implements Serializable {
    private static final long serialVersionUID = -1645880315099183738L;
    private Integer id;
    /**
     * key
     */
    private String sysKey;
    /**
     * value
     */
    private String sysValue;
    /**
     * 状态  1：有效 0：无效
     */
    private Integer status;
    /**
     * 备注
     */
    private String remark;

    @java.lang.SuppressWarnings("all")
    public SysConfig() {
    }

    @java.lang.SuppressWarnings("all")
    public Integer getId() {
        return this.id;
    }

    /**
     * key
     */
    @java.lang.SuppressWarnings("all")
    public String getSysKey() {
        return this.sysKey;
    }

    /**
     * value
     */
    @java.lang.SuppressWarnings("all")
    public String getSysValue() {
        return this.sysValue;
    }

    /**
     * 状态  1：有效 0：无效
     */
    @java.lang.SuppressWarnings("all")
    public Integer getStatus() {
        return this.status;
    }

    /**
     * 备注
     */
    @java.lang.SuppressWarnings("all")
    public String getRemark() {
        return this.remark;
    }

    @java.lang.SuppressWarnings("all")
    public SysConfig setId(final Integer id) {
        this.id = id;
        return this;
    }

    /**
     * key
     * @return this
     */
    @java.lang.SuppressWarnings("all")
    public SysConfig setSysKey(final String sysKey) {
        this.sysKey = sysKey;
        return this;
    }

    /**
     * value
     * @return this
     */
    @java.lang.SuppressWarnings("all")
    public SysConfig setSysValue(final String sysValue) {
        this.sysValue = sysValue;
        return this;
    }

    /**
     * 状态  1：有效 0：无效
     * @return this
     */
    @java.lang.SuppressWarnings("all")
    public SysConfig setStatus(final Integer status) {
        this.status = status;
        return this;
    }

    /**
     * 备注
     * @return this
     */
    @java.lang.SuppressWarnings("all")
    public SysConfig setRemark(final String remark) {
        this.remark = remark;
        return this;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof SysConfig)) return false;
        final SysConfig other = (SysConfig) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$sysKey = this.getSysKey();
        final java.lang.Object other$sysKey = other.getSysKey();
        if (this$sysKey == null ? other$sysKey != null : !this$sysKey.equals(other$sysKey)) return false;
        final java.lang.Object this$sysValue = this.getSysValue();
        final java.lang.Object other$sysValue = other.getSysValue();
        if (this$sysValue == null ? other$sysValue != null : !this$sysValue.equals(other$sysValue)) return false;
        final java.lang.Object this$status = this.getStatus();
        final java.lang.Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
        final java.lang.Object this$remark = this.getRemark();
        final java.lang.Object other$remark = other.getRemark();
        if (this$remark == null ? other$remark != null : !this$remark.equals(other$remark)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof SysConfig;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $sysKey = this.getSysKey();
        result = result * PRIME + ($sysKey == null ? 43 : $sysKey.hashCode());
        final java.lang.Object $sysValue = this.getSysValue();
        result = result * PRIME + ($sysValue == null ? 43 : $sysValue.hashCode());
        final java.lang.Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        final java.lang.Object $remark = this.getRemark();
        result = result * PRIME + ($remark == null ? 43 : $remark.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "SysConfig(id=" + this.getId() + ", sysKey=" + this.getSysKey() + ", sysValue=" + this.getSysValue() + ", status=" + this.getStatus() + ", remark=" + this.getRemark() + ")";
    }
}
