// Generated by delombok at Wed Apr 13 12:12:31 CST 2022
package com.puboot.module.admin.model;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import java.io.Serializable;
import java.util.Date;
import java.util.List;

/**
 * @author Linzhaoguan
 * @version V1.0
 * @date 2019年9月11日
 */
public class User implements Serializable {
    private static final long serialVersionUID = -8736616045315083846L;
    /**
     * 用户id
     */
    @TableId(type = IdType.UUID)
    private String userId;
    /**
     * 用户名
     */
    private String username;
    private String password;
    /**
     * 加密盐值
     */
    private String salt;
    /**
     * 昵称
     */
    private String nickname;
    /**
     * 邮箱
     */
    private String email;
    /**
     * 联系方式
     */
    private String phone;
    /**
     * 年龄：1男2女
     */
    private Integer sex;
    /**
     * 年龄
     */
    private Integer age;
    /**
     * 头像
     */
    private String img;
    /**
     * 用户状态：1有效; 0无效
     */
    private Integer status;
    /**
     * 创建时间
     */
    private Date createTime;
    /**
     * 更新时间
     */
    private Date updateTime;
    /**
     * 最后登录时间
     */
    private Date lastLoginTime;
    /**
     * 登录ip
     */
    @TableField(exist = false)
    private String loginIpAddress;
    /**
     * 角色
     */
    @TableField(exist = false)
    private List<Role> roles;

    /**
     * 重写获取盐值方法，自定义realm使用
     * Gets credentials salt.
     *
     * @return the credentials salt
     */
    public String getCredentialsSalt() {
        return username + "puboot.com" + salt;
    }

    @java.lang.SuppressWarnings("all")
    public User() {
    }

    /**
     * 用户id
     */
    @java.lang.SuppressWarnings("all")
    public String getUserId() {
        return this.userId;
    }

    /**
     * 用户名
     */
    @java.lang.SuppressWarnings("all")
    public String getUsername() {
        return this.username;
    }

    @java.lang.SuppressWarnings("all")
    public String getPassword() {
        return this.password;
    }

    /**
     * 加密盐值
     */
    @java.lang.SuppressWarnings("all")
    public String getSalt() {
        return this.salt;
    }

    /**
     * 昵称
     */
    @java.lang.SuppressWarnings("all")
    public String getNickname() {
        return this.nickname;
    }

    /**
     * 邮箱
     */
    @java.lang.SuppressWarnings("all")
    public String getEmail() {
        return this.email;
    }

    /**
     * 联系方式
     */
    @java.lang.SuppressWarnings("all")
    public String getPhone() {
        return this.phone;
    }

    /**
     * 年龄：1男2女
     */
    @java.lang.SuppressWarnings("all")
    public Integer getSex() {
        return this.sex;
    }

    /**
     * 年龄
     */
    @java.lang.SuppressWarnings("all")
    public Integer getAge() {
        return this.age;
    }

    /**
     * 头像
     */
    @java.lang.SuppressWarnings("all")
    public String getImg() {
        return this.img;
    }

    /**
     * 用户状态：1有效; 0无效
     */
    @java.lang.SuppressWarnings("all")
    public Integer getStatus() {
        return this.status;
    }

    /**
     * 创建时间
     */
    @java.lang.SuppressWarnings("all")
    public Date getCreateTime() {
        return this.createTime;
    }

    /**
     * 更新时间
     */
    @java.lang.SuppressWarnings("all")
    public Date getUpdateTime() {
        return this.updateTime;
    }

    /**
     * 最后登录时间
     */
    @java.lang.SuppressWarnings("all")
    public Date getLastLoginTime() {
        return this.lastLoginTime;
    }

    /**
     * 登录ip
     */
    @java.lang.SuppressWarnings("all")
    public String getLoginIpAddress() {
        return this.loginIpAddress;
    }

    /**
     * 角色
     */
    @java.lang.SuppressWarnings("all")
    public List<Role> getRoles() {
        return this.roles;
    }

    /**
     * 用户id
     */
    @java.lang.SuppressWarnings("all")
    public void setUserId(final String userId) {
        this.userId = userId;
    }

    /**
     * 用户名
     */
    @java.lang.SuppressWarnings("all")
    public void setUsername(final String username) {
        this.username = username;
    }

    @java.lang.SuppressWarnings("all")
    public void setPassword(final String password) {
        this.password = password;
    }

    /**
     * 加密盐值
     */
    @java.lang.SuppressWarnings("all")
    public void setSalt(final String salt) {
        this.salt = salt;
    }

    /**
     * 昵称
     */
    @java.lang.SuppressWarnings("all")
    public void setNickname(final String nickname) {
        this.nickname = nickname;
    }

    /**
     * 邮箱
     */
    @java.lang.SuppressWarnings("all")
    public void setEmail(final String email) {
        this.email = email;
    }

    /**
     * 联系方式
     */
    @java.lang.SuppressWarnings("all")
    public void setPhone(final String phone) {
        this.phone = phone;
    }

    /**
     * 年龄：1男2女
     */
    @java.lang.SuppressWarnings("all")
    public void setSex(final Integer sex) {
        this.sex = sex;
    }

    /**
     * 年龄
     */
    @java.lang.SuppressWarnings("all")
    public void setAge(final Integer age) {
        this.age = age;
    }

    /**
     * 头像
     */
    @java.lang.SuppressWarnings("all")
    public void setImg(final String img) {
        this.img = img;
    }

    /**
     * 用户状态：1有效; 0无效
     */
    @java.lang.SuppressWarnings("all")
    public void setStatus(final Integer status) {
        this.status = status;
    }

    /**
     * 创建时间
     */
    @java.lang.SuppressWarnings("all")
    public void setCreateTime(final Date createTime) {
        this.createTime = createTime;
    }

    /**
     * 更新时间
     */
    @java.lang.SuppressWarnings("all")
    public void setUpdateTime(final Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * 最后登录时间
     */
    @java.lang.SuppressWarnings("all")
    public void setLastLoginTime(final Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * 登录ip
     */
    @java.lang.SuppressWarnings("all")
    public void setLoginIpAddress(final String loginIpAddress) {
        this.loginIpAddress = loginIpAddress;
    }

    /**
     * 角色
     */
    @java.lang.SuppressWarnings("all")
    public void setRoles(final List<Role> roles) {
        this.roles = roles;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof User)) return false;
        final User other = (User) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$userId = this.getUserId();
        final java.lang.Object other$userId = other.getUserId();
        if (this$userId == null ? other$userId != null : !this$userId.equals(other$userId)) return false;
        final java.lang.Object this$username = this.getUsername();
        final java.lang.Object other$username = other.getUsername();
        if (this$username == null ? other$username != null : !this$username.equals(other$username)) return false;
        final java.lang.Object this$password = this.getPassword();
        final java.lang.Object other$password = other.getPassword();
        if (this$password == null ? other$password != null : !this$password.equals(other$password)) return false;
        final java.lang.Object this$salt = this.getSalt();
        final java.lang.Object other$salt = other.getSalt();
        if (this$salt == null ? other$salt != null : !this$salt.equals(other$salt)) return false;
        final java.lang.Object this$nickname = this.getNickname();
        final java.lang.Object other$nickname = other.getNickname();
        if (this$nickname == null ? other$nickname != null : !this$nickname.equals(other$nickname)) return false;
        final java.lang.Object this$email = this.getEmail();
        final java.lang.Object other$email = other.getEmail();
        if (this$email == null ? other$email != null : !this$email.equals(other$email)) return false;
        final java.lang.Object this$phone = this.getPhone();
        final java.lang.Object other$phone = other.getPhone();
        if (this$phone == null ? other$phone != null : !this$phone.equals(other$phone)) return false;
        final java.lang.Object this$sex = this.getSex();
        final java.lang.Object other$sex = other.getSex();
        if (this$sex == null ? other$sex != null : !this$sex.equals(other$sex)) return false;
        final java.lang.Object this$age = this.getAge();
        final java.lang.Object other$age = other.getAge();
        if (this$age == null ? other$age != null : !this$age.equals(other$age)) return false;
        final java.lang.Object this$img = this.getImg();
        final java.lang.Object other$img = other.getImg();
        if (this$img == null ? other$img != null : !this$img.equals(other$img)) return false;
        final java.lang.Object this$status = this.getStatus();
        final java.lang.Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
        final java.lang.Object this$createTime = this.getCreateTime();
        final java.lang.Object other$createTime = other.getCreateTime();
        if (this$createTime == null ? other$createTime != null : !this$createTime.equals(other$createTime)) return false;
        final java.lang.Object this$updateTime = this.getUpdateTime();
        final java.lang.Object other$updateTime = other.getUpdateTime();
        if (this$updateTime == null ? other$updateTime != null : !this$updateTime.equals(other$updateTime)) return false;
        final java.lang.Object this$lastLoginTime = this.getLastLoginTime();
        final java.lang.Object other$lastLoginTime = other.getLastLoginTime();
        if (this$lastLoginTime == null ? other$lastLoginTime != null : !this$lastLoginTime.equals(other$lastLoginTime)) return false;
        final java.lang.Object this$loginIpAddress = this.getLoginIpAddress();
        final java.lang.Object other$loginIpAddress = other.getLoginIpAddress();
        if (this$loginIpAddress == null ? other$loginIpAddress != null : !this$loginIpAddress.equals(other$loginIpAddress)) return false;
        final java.lang.Object this$roles = this.getRoles();
        final java.lang.Object other$roles = other.getRoles();
        if (this$roles == null ? other$roles != null : !this$roles.equals(other$roles)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof User;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $userId = this.getUserId();
        result = result * PRIME + ($userId == null ? 43 : $userId.hashCode());
        final java.lang.Object $username = this.getUsername();
        result = result * PRIME + ($username == null ? 43 : $username.hashCode());
        final java.lang.Object $password = this.getPassword();
        result = result * PRIME + ($password == null ? 43 : $password.hashCode());
        final java.lang.Object $salt = this.getSalt();
        result = result * PRIME + ($salt == null ? 43 : $salt.hashCode());
        final java.lang.Object $nickname = this.getNickname();
        result = result * PRIME + ($nickname == null ? 43 : $nickname.hashCode());
        final java.lang.Object $email = this.getEmail();
        result = result * PRIME + ($email == null ? 43 : $email.hashCode());
        final java.lang.Object $phone = this.getPhone();
        result = result * PRIME + ($phone == null ? 43 : $phone.hashCode());
        final java.lang.Object $sex = this.getSex();
        result = result * PRIME + ($sex == null ? 43 : $sex.hashCode());
        final java.lang.Object $age = this.getAge();
        result = result * PRIME + ($age == null ? 43 : $age.hashCode());
        final java.lang.Object $img = this.getImg();
        result = result * PRIME + ($img == null ? 43 : $img.hashCode());
        final java.lang.Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        final java.lang.Object $createTime = this.getCreateTime();
        result = result * PRIME + ($createTime == null ? 43 : $createTime.hashCode());
        final java.lang.Object $updateTime = this.getUpdateTime();
        result = result * PRIME + ($updateTime == null ? 43 : $updateTime.hashCode());
        final java.lang.Object $lastLoginTime = this.getLastLoginTime();
        result = result * PRIME + ($lastLoginTime == null ? 43 : $lastLoginTime.hashCode());
        final java.lang.Object $loginIpAddress = this.getLoginIpAddress();
        result = result * PRIME + ($loginIpAddress == null ? 43 : $loginIpAddress.hashCode());
        final java.lang.Object $roles = this.getRoles();
        result = result * PRIME + ($roles == null ? 43 : $roles.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "User(userId=" + this.getUserId() + ", username=" + this.getUsername() + ", password=" + this.getPassword() + ", salt=" + this.getSalt() + ", nickname=" + this.getNickname() + ", email=" + this.getEmail() + ", phone=" + this.getPhone() + ", sex=" + this.getSex() + ", age=" + this.getAge() + ", img=" + this.getImg() + ", status=" + this.getStatus() + ", createTime=" + this.getCreateTime() + ", updateTime=" + this.getUpdateTime() + ", lastLoginTime=" + this.getLastLoginTime() + ", loginIpAddress=" + this.getLoginIpAddress() + ", roles=" + this.getRoles() + ")";
    }
}
