// Generated by delombok at Wed Apr 13 12:12:31 CST 2022
package com.puboot.module.admin.service.impl;

import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.puboot.module.admin.mapper.BizLoveMapper;
import com.puboot.module.admin.model.BizLove;
import com.puboot.module.admin.service.BizLoveService;
import org.springframework.stereotype.Service;

/**
 * @author Linzhaoguan
 * @version V1.0
 * @date 2019年9月11日
 */
@Service
public class BizLoveServiceImpl extends ServiceImpl<BizLoveMapper, BizLove> implements BizLoveService {
    private final BizLoveMapper loveMapper;

    @Override
    public BizLove checkLove(Integer bizId, String userIp) {
        return loveMapper.checkLove(bizId, userIp);
    }

    @java.lang.SuppressWarnings("all")
    public BizLoveServiceImpl(final BizLoveMapper loveMapper) {
        this.loveMapper = loveMapper;
    }
}
