// Generated by delombok at Wed Apr 13 12:12:31 CST 2022
package com.puboot.module.admin.vo;

import com.puboot.module.admin.vo.base.BaseConditionVo;
import java.util.List;

/**
 * @author Linzhaoguan
 * @version V1.0
 * @date 2019年9月11日
 */
public class ArticleConditionVo extends BaseConditionVo {
    private Integer categoryId;
    private Integer tagId;
    private Integer status;
    private Boolean top;
    private Boolean recommended;
    private Boolean slider;
    private Boolean original;
    private Boolean random;
    private Boolean recentFlag;
    private Boolean sliderFlag;
    private List<Long> tagIds;
    private String keywords;

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof ArticleConditionVo)) return false;
        final ArticleConditionVo other = (ArticleConditionVo) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (!super.equals(o)) return false;
        final java.lang.Object this$categoryId = this.getCategoryId();
        final java.lang.Object other$categoryId = other.getCategoryId();
        if (this$categoryId == null ? other$categoryId != null : !this$categoryId.equals(other$categoryId)) return false;
        final java.lang.Object this$tagId = this.getTagId();
        final java.lang.Object other$tagId = other.getTagId();
        if (this$tagId == null ? other$tagId != null : !this$tagId.equals(other$tagId)) return false;
        final java.lang.Object this$status = this.getStatus();
        final java.lang.Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
        final java.lang.Object this$top = this.getTop();
        final java.lang.Object other$top = other.getTop();
        if (this$top == null ? other$top != null : !this$top.equals(other$top)) return false;
        final java.lang.Object this$recommended = this.getRecommended();
        final java.lang.Object other$recommended = other.getRecommended();
        if (this$recommended == null ? other$recommended != null : !this$recommended.equals(other$recommended)) return false;
        final java.lang.Object this$slider = this.getSlider();
        final java.lang.Object other$slider = other.getSlider();
        if (this$slider == null ? other$slider != null : !this$slider.equals(other$slider)) return false;
        final java.lang.Object this$original = this.getOriginal();
        final java.lang.Object other$original = other.getOriginal();
        if (this$original == null ? other$original != null : !this$original.equals(other$original)) return false;
        final java.lang.Object this$random = this.getRandom();
        final java.lang.Object other$random = other.getRandom();
        if (this$random == null ? other$random != null : !this$random.equals(other$random)) return false;
        final java.lang.Object this$recentFlag = this.getRecentFlag();
        final java.lang.Object other$recentFlag = other.getRecentFlag();
        if (this$recentFlag == null ? other$recentFlag != null : !this$recentFlag.equals(other$recentFlag)) return false;
        final java.lang.Object this$sliderFlag = this.getSliderFlag();
        final java.lang.Object other$sliderFlag = other.getSliderFlag();
        if (this$sliderFlag == null ? other$sliderFlag != null : !this$sliderFlag.equals(other$sliderFlag)) return false;
        final java.lang.Object this$tagIds = this.getTagIds();
        final java.lang.Object other$tagIds = other.getTagIds();
        if (this$tagIds == null ? other$tagIds != null : !this$tagIds.equals(other$tagIds)) return false;
        final java.lang.Object this$keywords = this.getKeywords();
        final java.lang.Object other$keywords = other.getKeywords();
        if (this$keywords == null ? other$keywords != null : !this$keywords.equals(other$keywords)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof ArticleConditionVo;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = super.hashCode();
        final java.lang.Object $categoryId = this.getCategoryId();
        result = result * PRIME + ($categoryId == null ? 43 : $categoryId.hashCode());
        final java.lang.Object $tagId = this.getTagId();
        result = result * PRIME + ($tagId == null ? 43 : $tagId.hashCode());
        final java.lang.Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        final java.lang.Object $top = this.getTop();
        result = result * PRIME + ($top == null ? 43 : $top.hashCode());
        final java.lang.Object $recommended = this.getRecommended();
        result = result * PRIME + ($recommended == null ? 43 : $recommended.hashCode());
        final java.lang.Object $slider = this.getSlider();
        result = result * PRIME + ($slider == null ? 43 : $slider.hashCode());
        final java.lang.Object $original = this.getOriginal();
        result = result * PRIME + ($original == null ? 43 : $original.hashCode());
        final java.lang.Object $random = this.getRandom();
        result = result * PRIME + ($random == null ? 43 : $random.hashCode());
        final java.lang.Object $recentFlag = this.getRecentFlag();
        result = result * PRIME + ($recentFlag == null ? 43 : $recentFlag.hashCode());
        final java.lang.Object $sliderFlag = this.getSliderFlag();
        result = result * PRIME + ($sliderFlag == null ? 43 : $sliderFlag.hashCode());
        final java.lang.Object $tagIds = this.getTagIds();
        result = result * PRIME + ($tagIds == null ? 43 : $tagIds.hashCode());
        final java.lang.Object $keywords = this.getKeywords();
        result = result * PRIME + ($keywords == null ? 43 : $keywords.hashCode());
        return result;
    }

    @java.lang.SuppressWarnings("all")
    public ArticleConditionVo() {
    }

    @java.lang.SuppressWarnings("all")
    public Integer getCategoryId() {
        return this.categoryId;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getTagId() {
        return this.tagId;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    public Boolean getTop() {
        return this.top;
    }

    @java.lang.SuppressWarnings("all")
    public Boolean getRecommended() {
        return this.recommended;
    }

    @java.lang.SuppressWarnings("all")
    public Boolean getSlider() {
        return this.slider;
    }

    @java.lang.SuppressWarnings("all")
    public Boolean getOriginal() {
        return this.original;
    }

    @java.lang.SuppressWarnings("all")
    public Boolean getRandom() {
        return this.random;
    }

    @java.lang.SuppressWarnings("all")
    public Boolean getRecentFlag() {
        return this.recentFlag;
    }

    @java.lang.SuppressWarnings("all")
    public Boolean getSliderFlag() {
        return this.sliderFlag;
    }

    @java.lang.SuppressWarnings("all")
    public List<Long> getTagIds() {
        return this.tagIds;
    }

    @java.lang.SuppressWarnings("all")
    public String getKeywords() {
        return this.keywords;
    }

    @java.lang.SuppressWarnings("all")
    public ArticleConditionVo setCategoryId(final Integer categoryId) {
        this.categoryId = categoryId;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public ArticleConditionVo setTagId(final Integer tagId) {
        this.tagId = tagId;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public ArticleConditionVo setStatus(final Integer status) {
        this.status = status;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public ArticleConditionVo setTop(final Boolean top) {
        this.top = top;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public ArticleConditionVo setRecommended(final Boolean recommended) {
        this.recommended = recommended;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public ArticleConditionVo setSlider(final Boolean slider) {
        this.slider = slider;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public ArticleConditionVo setOriginal(final Boolean original) {
        this.original = original;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public ArticleConditionVo setRandom(final Boolean random) {
        this.random = random;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public ArticleConditionVo setRecentFlag(final Boolean recentFlag) {
        this.recentFlag = recentFlag;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public ArticleConditionVo setSliderFlag(final Boolean sliderFlag) {
        this.sliderFlag = sliderFlag;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public ArticleConditionVo setTagIds(final List<Long> tagIds) {
        this.tagIds = tagIds;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    public ArticleConditionVo setKeywords(final String keywords) {
        this.keywords = keywords;
        return this;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "ArticleConditionVo(categoryId=" + this.getCategoryId() + ", tagId=" + this.getTagId() + ", status=" + this.getStatus() + ", top=" + this.getTop() + ", recommended=" + this.getRecommended() + ", slider=" + this.getSlider() + ", original=" + this.getOriginal() + ", random=" + this.getRandom() + ", recentFlag=" + this.getRecentFlag() + ", sliderFlag=" + this.getSliderFlag() + ", tagIds=" + this.getTagIds() + ", keywords=" + this.getKeywords() + ")";
    }
}
