// Generated by delombok at Wed Apr 13 12:12:31 CST 2022
package com.puboot.module.admin.vo;

/**
 * @author Linzhaoguan
 * @version V1.0
 * @date 2019年9月11日
 */
public class ChangePasswordVo {
    String oldPassword;
    String newPassword;
    String confirmNewPassword;

    @java.lang.SuppressWarnings("all")
    public ChangePasswordVo() {
    }

    @java.lang.SuppressWarnings("all")
    public String getOldPassword() {
        return this.oldPassword;
    }

    @java.lang.SuppressWarnings("all")
    public String getNewPassword() {
        return this.newPassword;
    }

    @java.lang.SuppressWarnings("all")
    public String getConfirmNewPassword() {
        return this.confirmNewPassword;
    }

    @java.lang.SuppressWarnings("all")
    public void setOldPassword(final String oldPassword) {
        this.oldPassword = oldPassword;
    }

    @java.lang.SuppressWarnings("all")
    public void setNewPassword(final String newPassword) {
        this.newPassword = newPassword;
    }

    @java.lang.SuppressWarnings("all")
    public void setConfirmNewPassword(final String confirmNewPassword) {
        this.confirmNewPassword = confirmNewPassword;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof ChangePasswordVo)) return false;
        final ChangePasswordVo other = (ChangePasswordVo) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$oldPassword = this.getOldPassword();
        final java.lang.Object other$oldPassword = other.getOldPassword();
        if (this$oldPassword == null ? other$oldPassword != null : !this$oldPassword.equals(other$oldPassword)) return false;
        final java.lang.Object this$newPassword = this.getNewPassword();
        final java.lang.Object other$newPassword = other.getNewPassword();
        if (this$newPassword == null ? other$newPassword != null : !this$newPassword.equals(other$newPassword)) return false;
        final java.lang.Object this$confirmNewPassword = this.getConfirmNewPassword();
        final java.lang.Object other$confirmNewPassword = other.getConfirmNewPassword();
        if (this$confirmNewPassword == null ? other$confirmNewPassword != null : !this$confirmNewPassword.equals(other$confirmNewPassword)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof ChangePasswordVo;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $oldPassword = this.getOldPassword();
        result = result * PRIME + ($oldPassword == null ? 43 : $oldPassword.hashCode());
        final java.lang.Object $newPassword = this.getNewPassword();
        result = result * PRIME + ($newPassword == null ? 43 : $newPassword.hashCode());
        final java.lang.Object $confirmNewPassword = this.getConfirmNewPassword();
        result = result * PRIME + ($confirmNewPassword == null ? 43 : $confirmNewPassword.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "ChangePasswordVo(oldPassword=" + this.getOldPassword() + ", newPassword=" + this.getNewPassword() + ", confirmNewPassword=" + this.getConfirmNewPassword() + ")";
    }
}
