// Generated by delombok at Wed Apr 13 12:12:31 CST 2022
package com.puboot.module.admin.vo;

/**
 * 云存储配置信息
 *
 * @author Linzhaoguan
 * @version V1.0
 * @date 2019年9月11日
 */
public class CloudStorageConfigVo {
    /**
     * 类型 1：七牛  2：阿里云  3：腾讯云  4：本地
     */
    private Integer type;
    //七牛绑定的域名
    private String qiniuDomain = "";
    //七牛路径前缀
    private String qiniuPrefix = "";
    //七牛ACCESS_KEY
    private String qiniuAccessKey = "";
    //七牛SECRET_KEY
    private String qiniuSecretKey = "";
    //七牛存储空间名
    private String qiniuBucketName = "";
    //阿里云绑定的域名
    private String aliyunDomain = "";
    //阿里云路径前缀
    private String aliyunPrefix = "";
    //阿里云EndPoint
    private String aliyunEndPoint = "";
    //阿里云AccessKeyId
    private String aliyunAccessKeyId = "";
    //阿里云AccessKeySecret
    private String aliyunAccessKeySecret = "";
    //阿里云BucketName
    private String aliyunBucketName = "";
    //腾讯云绑定的域名
    private String qcloudDomain = "";
    //腾讯云路径前缀
    private String qcloudPrefix = "";
    //腾讯云AppId
    private Integer qcloudAppId;
    //腾讯云SecretId
    private String qcloudSecretId = "";
    //腾讯云SecretKey
    private String qcloudSecretKey = "";
    //腾讯云BucketName
    private String qcloudBucketName = "";
    //腾讯云COS所属地区
    private String qcloudRegion = "";

    @java.lang.SuppressWarnings("all")
    public CloudStorageConfigVo() {
    }

    /**
     * 类型 1：七牛  2：阿里云  3：腾讯云  4：本地
     */
    @java.lang.SuppressWarnings("all")
    public Integer getType() {
        return this.type;
    }

    @java.lang.SuppressWarnings("all")
    public String getQiniuDomain() {
        return this.qiniuDomain;
    }

    @java.lang.SuppressWarnings("all")
    public String getQiniuPrefix() {
        return this.qiniuPrefix;
    }

    @java.lang.SuppressWarnings("all")
    public String getQiniuAccessKey() {
        return this.qiniuAccessKey;
    }

    @java.lang.SuppressWarnings("all")
    public String getQiniuSecretKey() {
        return this.qiniuSecretKey;
    }

    @java.lang.SuppressWarnings("all")
    public String getQiniuBucketName() {
        return this.qiniuBucketName;
    }

    @java.lang.SuppressWarnings("all")
    public String getAliyunDomain() {
        return this.aliyunDomain;
    }

    @java.lang.SuppressWarnings("all")
    public String getAliyunPrefix() {
        return this.aliyunPrefix;
    }

    @java.lang.SuppressWarnings("all")
    public String getAliyunEndPoint() {
        return this.aliyunEndPoint;
    }

    @java.lang.SuppressWarnings("all")
    public String getAliyunAccessKeyId() {
        return this.aliyunAccessKeyId;
    }

    @java.lang.SuppressWarnings("all")
    public String getAliyunAccessKeySecret() {
        return this.aliyunAccessKeySecret;
    }

    @java.lang.SuppressWarnings("all")
    public String getAliyunBucketName() {
        return this.aliyunBucketName;
    }

    @java.lang.SuppressWarnings("all")
    public String getQcloudDomain() {
        return this.qcloudDomain;
    }

    @java.lang.SuppressWarnings("all")
    public String getQcloudPrefix() {
        return this.qcloudPrefix;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getQcloudAppId() {
        return this.qcloudAppId;
    }

    @java.lang.SuppressWarnings("all")
    public String getQcloudSecretId() {
        return this.qcloudSecretId;
    }

    @java.lang.SuppressWarnings("all")
    public String getQcloudSecretKey() {
        return this.qcloudSecretKey;
    }

    @java.lang.SuppressWarnings("all")
    public String getQcloudBucketName() {
        return this.qcloudBucketName;
    }

    @java.lang.SuppressWarnings("all")
    public String getQcloudRegion() {
        return this.qcloudRegion;
    }

    /**
     * 类型 1：七牛  2：阿里云  3：腾讯云  4：本地
     */
    @java.lang.SuppressWarnings("all")
    public void setType(final Integer type) {
        this.type = type;
    }

    @java.lang.SuppressWarnings("all")
    public void setQiniuDomain(final String qiniuDomain) {
        this.qiniuDomain = qiniuDomain;
    }

    @java.lang.SuppressWarnings("all")
    public void setQiniuPrefix(final String qiniuPrefix) {
        this.qiniuPrefix = qiniuPrefix;
    }

    @java.lang.SuppressWarnings("all")
    public void setQiniuAccessKey(final String qiniuAccessKey) {
        this.qiniuAccessKey = qiniuAccessKey;
    }

    @java.lang.SuppressWarnings("all")
    public void setQiniuSecretKey(final String qiniuSecretKey) {
        this.qiniuSecretKey = qiniuSecretKey;
    }

    @java.lang.SuppressWarnings("all")
    public void setQiniuBucketName(final String qiniuBucketName) {
        this.qiniuBucketName = qiniuBucketName;
    }

    @java.lang.SuppressWarnings("all")
    public void setAliyunDomain(final String aliyunDomain) {
        this.aliyunDomain = aliyunDomain;
    }

    @java.lang.SuppressWarnings("all")
    public void setAliyunPrefix(final String aliyunPrefix) {
        this.aliyunPrefix = aliyunPrefix;
    }

    @java.lang.SuppressWarnings("all")
    public void setAliyunEndPoint(final String aliyunEndPoint) {
        this.aliyunEndPoint = aliyunEndPoint;
    }

    @java.lang.SuppressWarnings("all")
    public void setAliyunAccessKeyId(final String aliyunAccessKeyId) {
        this.aliyunAccessKeyId = aliyunAccessKeyId;
    }

    @java.lang.SuppressWarnings("all")
    public void setAliyunAccessKeySecret(final String aliyunAccessKeySecret) {
        this.aliyunAccessKeySecret = aliyunAccessKeySecret;
    }

    @java.lang.SuppressWarnings("all")
    public void setAliyunBucketName(final String aliyunBucketName) {
        this.aliyunBucketName = aliyunBucketName;
    }

    @java.lang.SuppressWarnings("all")
    public void setQcloudDomain(final String qcloudDomain) {
        this.qcloudDomain = qcloudDomain;
    }

    @java.lang.SuppressWarnings("all")
    public void setQcloudPrefix(final String qcloudPrefix) {
        this.qcloudPrefix = qcloudPrefix;
    }

    @java.lang.SuppressWarnings("all")
    public void setQcloudAppId(final Integer qcloudAppId) {
        this.qcloudAppId = qcloudAppId;
    }

    @java.lang.SuppressWarnings("all")
    public void setQcloudSecretId(final String qcloudSecretId) {
        this.qcloudSecretId = qcloudSecretId;
    }

    @java.lang.SuppressWarnings("all")
    public void setQcloudSecretKey(final String qcloudSecretKey) {
        this.qcloudSecretKey = qcloudSecretKey;
    }

    @java.lang.SuppressWarnings("all")
    public void setQcloudBucketName(final String qcloudBucketName) {
        this.qcloudBucketName = qcloudBucketName;
    }

    @java.lang.SuppressWarnings("all")
    public void setQcloudRegion(final String qcloudRegion) {
        this.qcloudRegion = qcloudRegion;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof CloudStorageConfigVo)) return false;
        final CloudStorageConfigVo other = (CloudStorageConfigVo) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$type = this.getType();
        final java.lang.Object other$type = other.getType();
        if (this$type == null ? other$type != null : !this$type.equals(other$type)) return false;
        final java.lang.Object this$qiniuDomain = this.getQiniuDomain();
        final java.lang.Object other$qiniuDomain = other.getQiniuDomain();
        if (this$qiniuDomain == null ? other$qiniuDomain != null : !this$qiniuDomain.equals(other$qiniuDomain)) return false;
        final java.lang.Object this$qiniuPrefix = this.getQiniuPrefix();
        final java.lang.Object other$qiniuPrefix = other.getQiniuPrefix();
        if (this$qiniuPrefix == null ? other$qiniuPrefix != null : !this$qiniuPrefix.equals(other$qiniuPrefix)) return false;
        final java.lang.Object this$qiniuAccessKey = this.getQiniuAccessKey();
        final java.lang.Object other$qiniuAccessKey = other.getQiniuAccessKey();
        if (this$qiniuAccessKey == null ? other$qiniuAccessKey != null : !this$qiniuAccessKey.equals(other$qiniuAccessKey)) return false;
        final java.lang.Object this$qiniuSecretKey = this.getQiniuSecretKey();
        final java.lang.Object other$qiniuSecretKey = other.getQiniuSecretKey();
        if (this$qiniuSecretKey == null ? other$qiniuSecretKey != null : !this$qiniuSecretKey.equals(other$qiniuSecretKey)) return false;
        final java.lang.Object this$qiniuBucketName = this.getQiniuBucketName();
        final java.lang.Object other$qiniuBucketName = other.getQiniuBucketName();
        if (this$qiniuBucketName == null ? other$qiniuBucketName != null : !this$qiniuBucketName.equals(other$qiniuBucketName)) return false;
        final java.lang.Object this$aliyunDomain = this.getAliyunDomain();
        final java.lang.Object other$aliyunDomain = other.getAliyunDomain();
        if (this$aliyunDomain == null ? other$aliyunDomain != null : !this$aliyunDomain.equals(other$aliyunDomain)) return false;
        final java.lang.Object this$aliyunPrefix = this.getAliyunPrefix();
        final java.lang.Object other$aliyunPrefix = other.getAliyunPrefix();
        if (this$aliyunPrefix == null ? other$aliyunPrefix != null : !this$aliyunPrefix.equals(other$aliyunPrefix)) return false;
        final java.lang.Object this$aliyunEndPoint = this.getAliyunEndPoint();
        final java.lang.Object other$aliyunEndPoint = other.getAliyunEndPoint();
        if (this$aliyunEndPoint == null ? other$aliyunEndPoint != null : !this$aliyunEndPoint.equals(other$aliyunEndPoint)) return false;
        final java.lang.Object this$aliyunAccessKeyId = this.getAliyunAccessKeyId();
        final java.lang.Object other$aliyunAccessKeyId = other.getAliyunAccessKeyId();
        if (this$aliyunAccessKeyId == null ? other$aliyunAccessKeyId != null : !this$aliyunAccessKeyId.equals(other$aliyunAccessKeyId)) return false;
        final java.lang.Object this$aliyunAccessKeySecret = this.getAliyunAccessKeySecret();
        final java.lang.Object other$aliyunAccessKeySecret = other.getAliyunAccessKeySecret();
        if (this$aliyunAccessKeySecret == null ? other$aliyunAccessKeySecret != null : !this$aliyunAccessKeySecret.equals(other$aliyunAccessKeySecret)) return false;
        final java.lang.Object this$aliyunBucketName = this.getAliyunBucketName();
        final java.lang.Object other$aliyunBucketName = other.getAliyunBucketName();
        if (this$aliyunBucketName == null ? other$aliyunBucketName != null : !this$aliyunBucketName.equals(other$aliyunBucketName)) return false;
        final java.lang.Object this$qcloudDomain = this.getQcloudDomain();
        final java.lang.Object other$qcloudDomain = other.getQcloudDomain();
        if (this$qcloudDomain == null ? other$qcloudDomain != null : !this$qcloudDomain.equals(other$qcloudDomain)) return false;
        final java.lang.Object this$qcloudPrefix = this.getQcloudPrefix();
        final java.lang.Object other$qcloudPrefix = other.getQcloudPrefix();
        if (this$qcloudPrefix == null ? other$qcloudPrefix != null : !this$qcloudPrefix.equals(other$qcloudPrefix)) return false;
        final java.lang.Object this$qcloudAppId = this.getQcloudAppId();
        final java.lang.Object other$qcloudAppId = other.getQcloudAppId();
        if (this$qcloudAppId == null ? other$qcloudAppId != null : !this$qcloudAppId.equals(other$qcloudAppId)) return false;
        final java.lang.Object this$qcloudSecretId = this.getQcloudSecretId();
        final java.lang.Object other$qcloudSecretId = other.getQcloudSecretId();
        if (this$qcloudSecretId == null ? other$qcloudSecretId != null : !this$qcloudSecretId.equals(other$qcloudSecretId)) return false;
        final java.lang.Object this$qcloudSecretKey = this.getQcloudSecretKey();
        final java.lang.Object other$qcloudSecretKey = other.getQcloudSecretKey();
        if (this$qcloudSecretKey == null ? other$qcloudSecretKey != null : !this$qcloudSecretKey.equals(other$qcloudSecretKey)) return false;
        final java.lang.Object this$qcloudBucketName = this.getQcloudBucketName();
        final java.lang.Object other$qcloudBucketName = other.getQcloudBucketName();
        if (this$qcloudBucketName == null ? other$qcloudBucketName != null : !this$qcloudBucketName.equals(other$qcloudBucketName)) return false;
        final java.lang.Object this$qcloudRegion = this.getQcloudRegion();
        final java.lang.Object other$qcloudRegion = other.getQcloudRegion();
        if (this$qcloudRegion == null ? other$qcloudRegion != null : !this$qcloudRegion.equals(other$qcloudRegion)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof CloudStorageConfigVo;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $type = this.getType();
        result = result * PRIME + ($type == null ? 43 : $type.hashCode());
        final java.lang.Object $qiniuDomain = this.getQiniuDomain();
        result = result * PRIME + ($qiniuDomain == null ? 43 : $qiniuDomain.hashCode());
        final java.lang.Object $qiniuPrefix = this.getQiniuPrefix();
        result = result * PRIME + ($qiniuPrefix == null ? 43 : $qiniuPrefix.hashCode());
        final java.lang.Object $qiniuAccessKey = this.getQiniuAccessKey();
        result = result * PRIME + ($qiniuAccessKey == null ? 43 : $qiniuAccessKey.hashCode());
        final java.lang.Object $qiniuSecretKey = this.getQiniuSecretKey();
        result = result * PRIME + ($qiniuSecretKey == null ? 43 : $qiniuSecretKey.hashCode());
        final java.lang.Object $qiniuBucketName = this.getQiniuBucketName();
        result = result * PRIME + ($qiniuBucketName == null ? 43 : $qiniuBucketName.hashCode());
        final java.lang.Object $aliyunDomain = this.getAliyunDomain();
        result = result * PRIME + ($aliyunDomain == null ? 43 : $aliyunDomain.hashCode());
        final java.lang.Object $aliyunPrefix = this.getAliyunPrefix();
        result = result * PRIME + ($aliyunPrefix == null ? 43 : $aliyunPrefix.hashCode());
        final java.lang.Object $aliyunEndPoint = this.getAliyunEndPoint();
        result = result * PRIME + ($aliyunEndPoint == null ? 43 : $aliyunEndPoint.hashCode());
        final java.lang.Object $aliyunAccessKeyId = this.getAliyunAccessKeyId();
        result = result * PRIME + ($aliyunAccessKeyId == null ? 43 : $aliyunAccessKeyId.hashCode());
        final java.lang.Object $aliyunAccessKeySecret = this.getAliyunAccessKeySecret();
        result = result * PRIME + ($aliyunAccessKeySecret == null ? 43 : $aliyunAccessKeySecret.hashCode());
        final java.lang.Object $aliyunBucketName = this.getAliyunBucketName();
        result = result * PRIME + ($aliyunBucketName == null ? 43 : $aliyunBucketName.hashCode());
        final java.lang.Object $qcloudDomain = this.getQcloudDomain();
        result = result * PRIME + ($qcloudDomain == null ? 43 : $qcloudDomain.hashCode());
        final java.lang.Object $qcloudPrefix = this.getQcloudPrefix();
        result = result * PRIME + ($qcloudPrefix == null ? 43 : $qcloudPrefix.hashCode());
        final java.lang.Object $qcloudAppId = this.getQcloudAppId();
        result = result * PRIME + ($qcloudAppId == null ? 43 : $qcloudAppId.hashCode());
        final java.lang.Object $qcloudSecretId = this.getQcloudSecretId();
        result = result * PRIME + ($qcloudSecretId == null ? 43 : $qcloudSecretId.hashCode());
        final java.lang.Object $qcloudSecretKey = this.getQcloudSecretKey();
        result = result * PRIME + ($qcloudSecretKey == null ? 43 : $qcloudSecretKey.hashCode());
        final java.lang.Object $qcloudBucketName = this.getQcloudBucketName();
        result = result * PRIME + ($qcloudBucketName == null ? 43 : $qcloudBucketName.hashCode());
        final java.lang.Object $qcloudRegion = this.getQcloudRegion();
        result = result * PRIME + ($qcloudRegion == null ? 43 : $qcloudRegion.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "CloudStorageConfigVo(type=" + this.getType() + ", qiniuDomain=" + this.getQiniuDomain() + ", qiniuPrefix=" + this.getQiniuPrefix() + ", qiniuAccessKey=" + this.getQiniuAccessKey() + ", qiniuSecretKey=" + this.getQiniuSecretKey() + ", qiniuBucketName=" + this.getQiniuBucketName() + ", aliyunDomain=" + this.getAliyunDomain() + ", aliyunPrefix=" + this.getAliyunPrefix() + ", aliyunEndPoint=" + this.getAliyunEndPoint() + ", aliyunAccessKeyId=" + this.getAliyunAccessKeyId() + ", aliyunAccessKeySecret=" + this.getAliyunAccessKeySecret() + ", aliyunBucketName=" + this.getAliyunBucketName() + ", qcloudDomain=" + this.getQcloudDomain() + ", qcloudPrefix=" + this.getQcloudPrefix() + ", qcloudAppId=" + this.getQcloudAppId() + ", qcloudSecretId=" + this.getQcloudSecretId() + ", qcloudSecretKey=" + this.getQcloudSecretKey() + ", qcloudBucketName=" + this.getQcloudBucketName() + ", qcloudRegion=" + this.getQcloudRegion() + ")";
    }
}
