// Generated by delombok at Wed Apr 13 12:12:31 CST 2022
package com.puboot.module.admin.vo;

public class CountVo {
    private String day;
    private Integer count;

    @java.lang.SuppressWarnings("all")
    public CountVo() {
    }

    @java.lang.SuppressWarnings("all")
    public String getDay() {
        return this.day;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getCount() {
        return this.count;
    }

    @java.lang.SuppressWarnings("all")
    public void setDay(final String day) {
        this.day = day;
    }

    @java.lang.SuppressWarnings("all")
    public void setCount(final Integer count) {
        this.count = count;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof CountVo)) return false;
        final CountVo other = (CountVo) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$day = this.getDay();
        final java.lang.Object other$day = other.getDay();
        if (this$day == null ? other$day != null : !this$day.equals(other$day)) return false;
        final java.lang.Object this$count = this.getCount();
        final java.lang.Object other$count = other.getCount();
        if (this$count == null ? other$count != null : !this$count.equals(other$count)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof CountVo;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $day = this.getDay();
        result = result * PRIME + ($day == null ? 43 : $day.hashCode());
        final java.lang.Object $count = this.getCount();
        result = result * PRIME + ($count == null ? 43 : $count.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "CountVo(day=" + this.getDay() + ", count=" + this.getCount() + ")";
    }
}
