// Generated by delombok at Wed Apr 13 12:12:31 CST 2022
package com.puboot.module.admin.vo;

import java.util.Map;

/**
 * Created with IntelliJ IDEA.
 *
 * @author Nobita
 * @date 2021/1/12 3:35 下午
 */
public class StatisticVo {
    private Integer articleCount;
    private Integer commentCount;
    private Integer lookCount;
    private Integer userCount;
    private Map<String, Integer> lookCountByDay;
    private Map<String, Integer> userCountByDay;

    @java.lang.SuppressWarnings("all")
    StatisticVo(final Integer articleCount, final Integer commentCount, final Integer lookCount, final Integer userCount, final Map<String, Integer> lookCountByDay, final Map<String, Integer> userCountByDay) {
        this.articleCount = articleCount;
        this.commentCount = commentCount;
        this.lookCount = lookCount;
        this.userCount = userCount;
        this.lookCountByDay = lookCountByDay;
        this.userCountByDay = userCountByDay;
    }


    @java.lang.SuppressWarnings("all")
    public static class StatisticVoBuilder {
        @java.lang.SuppressWarnings("all")
        private Integer articleCount;
        @java.lang.SuppressWarnings("all")
        private Integer commentCount;
        @java.lang.SuppressWarnings("all")
        private Integer lookCount;
        @java.lang.SuppressWarnings("all")
        private Integer userCount;
        @java.lang.SuppressWarnings("all")
        private Map<String, Integer> lookCountByDay;
        @java.lang.SuppressWarnings("all")
        private Map<String, Integer> userCountByDay;

        @java.lang.SuppressWarnings("all")
        StatisticVoBuilder() {
        }

        @java.lang.SuppressWarnings("all")
        public StatisticVoBuilder articleCount(final Integer articleCount) {
            this.articleCount = articleCount;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public StatisticVoBuilder commentCount(final Integer commentCount) {
            this.commentCount = commentCount;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public StatisticVoBuilder lookCount(final Integer lookCount) {
            this.lookCount = lookCount;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public StatisticVoBuilder userCount(final Integer userCount) {
            this.userCount = userCount;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public StatisticVoBuilder lookCountByDay(final Map<String, Integer> lookCountByDay) {
            this.lookCountByDay = lookCountByDay;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public StatisticVoBuilder userCountByDay(final Map<String, Integer> userCountByDay) {
            this.userCountByDay = userCountByDay;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public StatisticVo build() {
            return new StatisticVo(articleCount, commentCount, lookCount, userCount, lookCountByDay, userCountByDay);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "StatisticVo.StatisticVoBuilder(articleCount=" + this.articleCount + ", commentCount=" + this.commentCount + ", lookCount=" + this.lookCount + ", userCount=" + this.userCount + ", lookCountByDay=" + this.lookCountByDay + ", userCountByDay=" + this.userCountByDay + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static StatisticVoBuilder builder() {
        return new StatisticVoBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public Integer getArticleCount() {
        return this.articleCount;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getCommentCount() {
        return this.commentCount;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getLookCount() {
        return this.lookCount;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getUserCount() {
        return this.userCount;
    }

    @java.lang.SuppressWarnings("all")
    public Map<String, Integer> getLookCountByDay() {
        return this.lookCountByDay;
    }

    @java.lang.SuppressWarnings("all")
    public Map<String, Integer> getUserCountByDay() {
        return this.userCountByDay;
    }

    @java.lang.SuppressWarnings("all")
    public void setArticleCount(final Integer articleCount) {
        this.articleCount = articleCount;
    }

    @java.lang.SuppressWarnings("all")
    public void setCommentCount(final Integer commentCount) {
        this.commentCount = commentCount;
    }

    @java.lang.SuppressWarnings("all")
    public void setLookCount(final Integer lookCount) {
        this.lookCount = lookCount;
    }

    @java.lang.SuppressWarnings("all")
    public void setUserCount(final Integer userCount) {
        this.userCount = userCount;
    }

    @java.lang.SuppressWarnings("all")
    public void setLookCountByDay(final Map<String, Integer> lookCountByDay) {
        this.lookCountByDay = lookCountByDay;
    }

    @java.lang.SuppressWarnings("all")
    public void setUserCountByDay(final Map<String, Integer> userCountByDay) {
        this.userCountByDay = userCountByDay;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof StatisticVo)) return false;
        final StatisticVo other = (StatisticVo) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$articleCount = this.getArticleCount();
        final java.lang.Object other$articleCount = other.getArticleCount();
        if (this$articleCount == null ? other$articleCount != null : !this$articleCount.equals(other$articleCount)) return false;
        final java.lang.Object this$commentCount = this.getCommentCount();
        final java.lang.Object other$commentCount = other.getCommentCount();
        if (this$commentCount == null ? other$commentCount != null : !this$commentCount.equals(other$commentCount)) return false;
        final java.lang.Object this$lookCount = this.getLookCount();
        final java.lang.Object other$lookCount = other.getLookCount();
        if (this$lookCount == null ? other$lookCount != null : !this$lookCount.equals(other$lookCount)) return false;
        final java.lang.Object this$userCount = this.getUserCount();
        final java.lang.Object other$userCount = other.getUserCount();
        if (this$userCount == null ? other$userCount != null : !this$userCount.equals(other$userCount)) return false;
        final java.lang.Object this$lookCountByDay = this.getLookCountByDay();
        final java.lang.Object other$lookCountByDay = other.getLookCountByDay();
        if (this$lookCountByDay == null ? other$lookCountByDay != null : !this$lookCountByDay.equals(other$lookCountByDay)) return false;
        final java.lang.Object this$userCountByDay = this.getUserCountByDay();
        final java.lang.Object other$userCountByDay = other.getUserCountByDay();
        if (this$userCountByDay == null ? other$userCountByDay != null : !this$userCountByDay.equals(other$userCountByDay)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof StatisticVo;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $articleCount = this.getArticleCount();
        result = result * PRIME + ($articleCount == null ? 43 : $articleCount.hashCode());
        final java.lang.Object $commentCount = this.getCommentCount();
        result = result * PRIME + ($commentCount == null ? 43 : $commentCount.hashCode());
        final java.lang.Object $lookCount = this.getLookCount();
        result = result * PRIME + ($lookCount == null ? 43 : $lookCount.hashCode());
        final java.lang.Object $userCount = this.getUserCount();
        result = result * PRIME + ($userCount == null ? 43 : $userCount.hashCode());
        final java.lang.Object $lookCountByDay = this.getLookCountByDay();
        result = result * PRIME + ($lookCountByDay == null ? 43 : $lookCountByDay.hashCode());
        final java.lang.Object $userCountByDay = this.getUserCountByDay();
        result = result * PRIME + ($userCountByDay == null ? 43 : $userCountByDay.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "StatisticVo(articleCount=" + this.getArticleCount() + ", commentCount=" + this.getCommentCount() + ", lookCount=" + this.getLookCount() + ", userCount=" + this.getUserCount() + ", lookCountByDay=" + this.getLookCountByDay() + ", userCountByDay=" + this.getUserCountByDay() + ")";
    }
}
