// Generated by delombok at Wed Apr 13 12:12:31 CST 2022
package com.puboot.module.admin.vo;

import java.io.Serializable;
import java.util.Date;

/**
 * @author Linzhaoguan
 * @version V1.0
 * @date 2019年9月11日
 */
public class UserOnlineVo implements Serializable {
    private static final long serialVersionUID = 1L;
    //Session Id
    private String sessionId;
    //username
    private String username;
    //Session Host
    private String host;
    //Session创建时间
    private Date startTime;
    //Session最后交互时间
    private Date lastAccess;
    /*最后登录时间*/
    private Date lastLoginTime;
    //Session timeout
    private long timeout;
    //session 是否踢出
    private boolean sessionStatus = Boolean.TRUE;

    @java.lang.SuppressWarnings("all")
    public UserOnlineVo() {
    }

    @java.lang.SuppressWarnings("all")
    public String getSessionId() {
        return this.sessionId;
    }

    @java.lang.SuppressWarnings("all")
    public String getUsername() {
        return this.username;
    }

    @java.lang.SuppressWarnings("all")
    public String getHost() {
        return this.host;
    }

    @java.lang.SuppressWarnings("all")
    public Date getStartTime() {
        return this.startTime;
    }

    @java.lang.SuppressWarnings("all")
    public Date getLastAccess() {
        return this.lastAccess;
    }

    @java.lang.SuppressWarnings("all")
    public Date getLastLoginTime() {
        return this.lastLoginTime;
    }

    @java.lang.SuppressWarnings("all")
    public long getTimeout() {
        return this.timeout;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isSessionStatus() {
        return this.sessionStatus;
    }

    @java.lang.SuppressWarnings("all")
    public void setSessionId(final String sessionId) {
        this.sessionId = sessionId;
    }

    @java.lang.SuppressWarnings("all")
    public void setUsername(final String username) {
        this.username = username;
    }

    @java.lang.SuppressWarnings("all")
    public void setHost(final String host) {
        this.host = host;
    }

    @java.lang.SuppressWarnings("all")
    public void setStartTime(final Date startTime) {
        this.startTime = startTime;
    }

    @java.lang.SuppressWarnings("all")
    public void setLastAccess(final Date lastAccess) {
        this.lastAccess = lastAccess;
    }

    @java.lang.SuppressWarnings("all")
    public void setLastLoginTime(final Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    @java.lang.SuppressWarnings("all")
    public void setTimeout(final long timeout) {
        this.timeout = timeout;
    }

    @java.lang.SuppressWarnings("all")
    public void setSessionStatus(final boolean sessionStatus) {
        this.sessionStatus = sessionStatus;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof UserOnlineVo)) return false;
        final UserOnlineVo other = (UserOnlineVo) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$sessionId = this.getSessionId();
        final java.lang.Object other$sessionId = other.getSessionId();
        if (this$sessionId == null ? other$sessionId != null : !this$sessionId.equals(other$sessionId)) return false;
        final java.lang.Object this$username = this.getUsername();
        final java.lang.Object other$username = other.getUsername();
        if (this$username == null ? other$username != null : !this$username.equals(other$username)) return false;
        final java.lang.Object this$host = this.getHost();
        final java.lang.Object other$host = other.getHost();
        if (this$host == null ? other$host != null : !this$host.equals(other$host)) return false;
        final java.lang.Object this$startTime = this.getStartTime();
        final java.lang.Object other$startTime = other.getStartTime();
        if (this$startTime == null ? other$startTime != null : !this$startTime.equals(other$startTime)) return false;
        final java.lang.Object this$lastAccess = this.getLastAccess();
        final java.lang.Object other$lastAccess = other.getLastAccess();
        if (this$lastAccess == null ? other$lastAccess != null : !this$lastAccess.equals(other$lastAccess)) return false;
        final java.lang.Object this$lastLoginTime = this.getLastLoginTime();
        final java.lang.Object other$lastLoginTime = other.getLastLoginTime();
        if (this$lastLoginTime == null ? other$lastLoginTime != null : !this$lastLoginTime.equals(other$lastLoginTime)) return false;
        if (this.getTimeout() != other.getTimeout()) return false;
        if (this.isSessionStatus() != other.isSessionStatus()) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof UserOnlineVo;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $sessionId = this.getSessionId();
        result = result * PRIME + ($sessionId == null ? 43 : $sessionId.hashCode());
        final java.lang.Object $username = this.getUsername();
        result = result * PRIME + ($username == null ? 43 : $username.hashCode());
        final java.lang.Object $host = this.getHost();
        result = result * PRIME + ($host == null ? 43 : $host.hashCode());
        final java.lang.Object $startTime = this.getStartTime();
        result = result * PRIME + ($startTime == null ? 43 : $startTime.hashCode());
        final java.lang.Object $lastAccess = this.getLastAccess();
        result = result * PRIME + ($lastAccess == null ? 43 : $lastAccess.hashCode());
        final java.lang.Object $lastLoginTime = this.getLastLoginTime();
        result = result * PRIME + ($lastLoginTime == null ? 43 : $lastLoginTime.hashCode());
        final long $timeout = this.getTimeout();
        result = result * PRIME + (int) ($timeout >>> 32 ^ $timeout);
        result = result * PRIME + (this.isSessionStatus() ? 79 : 97);
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "UserOnlineVo(sessionId=" + this.getSessionId() + ", username=" + this.getUsername() + ", host=" + this.getHost() + ", startTime=" + this.getStartTime() + ", lastAccess=" + this.getLastAccess() + ", lastLoginTime=" + this.getLastLoginTime() + ", timeout=" + this.getTimeout() + ", sessionStatus=" + this.isSessionStatus() + ")";
    }
}
