// Generated by delombok at Wed Apr 13 12:12:31 CST 2022
package com.puboot.common.config.properties;

import org.springframework.boot.context.properties.ConfigurationProperties;

/**
 * Created with IntelliJ IDEA.
 *
 * @author Nobita
 * @date 2020/4/18 12:10 下午
 */
@ConfigurationProperties(prefix = "file")
public class FileUploadProperties {
    private String accessPathPattern = "/u/**";
    private String uploadFolder;
    private String accessPrefixUrl;

    @java.lang.SuppressWarnings("all")
    public FileUploadProperties() {
    }

    @java.lang.SuppressWarnings("all")
    public String getAccessPathPattern() {
        return this.accessPathPattern;
    }

    @java.lang.SuppressWarnings("all")
    public String getUploadFolder() {
        return this.uploadFolder;
    }

    @java.lang.SuppressWarnings("all")
    public String getAccessPrefixUrl() {
        return this.accessPrefixUrl;
    }

    @java.lang.SuppressWarnings("all")
    public void setAccessPathPattern(final String accessPathPattern) {
        this.accessPathPattern = accessPathPattern;
    }

    @java.lang.SuppressWarnings("all")
    public void setUploadFolder(final String uploadFolder) {
        this.uploadFolder = uploadFolder;
    }

    @java.lang.SuppressWarnings("all")
    public void setAccessPrefixUrl(final String accessPrefixUrl) {
        this.accessPrefixUrl = accessPrefixUrl;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof FileUploadProperties)) return false;
        final FileUploadProperties other = (FileUploadProperties) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$accessPathPattern = this.getAccessPathPattern();
        final java.lang.Object other$accessPathPattern = other.getAccessPathPattern();
        if (this$accessPathPattern == null ? other$accessPathPattern != null : !this$accessPathPattern.equals(other$accessPathPattern)) return false;
        final java.lang.Object this$uploadFolder = this.getUploadFolder();
        final java.lang.Object other$uploadFolder = other.getUploadFolder();
        if (this$uploadFolder == null ? other$uploadFolder != null : !this$uploadFolder.equals(other$uploadFolder)) return false;
        final java.lang.Object this$accessPrefixUrl = this.getAccessPrefixUrl();
        final java.lang.Object other$accessPrefixUrl = other.getAccessPrefixUrl();
        if (this$accessPrefixUrl == null ? other$accessPrefixUrl != null : !this$accessPrefixUrl.equals(other$accessPrefixUrl)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof FileUploadProperties;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $accessPathPattern = this.getAccessPathPattern();
        result = result * PRIME + ($accessPathPattern == null ? 43 : $accessPathPattern.hashCode());
        final java.lang.Object $uploadFolder = this.getUploadFolder();
        result = result * PRIME + ($uploadFolder == null ? 43 : $uploadFolder.hashCode());
        final java.lang.Object $accessPrefixUrl = this.getAccessPrefixUrl();
        result = result * PRIME + ($accessPrefixUrl == null ? 43 : $accessPrefixUrl.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "FileUploadProperties(accessPathPattern=" + this.getAccessPathPattern() + ", uploadFolder=" + this.getUploadFolder() + ", accessPrefixUrl=" + this.getAccessPrefixUrl() + ")";
    }
}
