// Generated by delombok at Wed Apr 13 12:12:31 CST 2022
package com.puboot.enums;

/**
 * 接口响应状态枚举类
 *
 * @author Linzhaoguan
 * @version V1.0
 * @date 2019年9月11日
 */
public enum ResponseStatus {
    /**
     * 操作成功
     */
    SUCCESS(200, "操作成功！"), /**
     * 无权限
     */
    FORBIDDEN(403, "您没有权限访问！"), /**
     * 未找到
     */
    NOT_FOUND(404, "资源不存在！"), /**
     * 服务器内部错误
     */
    ERROR(500, "服务器内部错误！");
    private final Integer code;
    private final String message;

    @java.lang.SuppressWarnings("all")
    public Integer getCode() {
        return this.code;
    }

    @java.lang.SuppressWarnings("all")
    public String getMessage() {
        return this.message;
    }

    @java.lang.SuppressWarnings("all")
    private ResponseStatus(final Integer code, final String message) {
        this.code = code;
        this.message = message;
    }
}
